delimiter ;
insert ignore into ds_pug_templates (name,id,note,template) 
values ('page','page',from_base64('cGFnZQ=='),from_base64( 'ZXh0ZW5kcyBwYWdlLW1haW4KaW5jbHVkZSBwYWdlLW1peGluLWNoZWNrYm94CmluY2x1ZGUgcGFn
ZS1taXhpbi1iYWxsb3RwYXBlci1tYXgKCmJsb2NrIGNvbnRlbnQKCWNhc2UgY21zLndtcy5nZXRO
ZXh0U3RhdGUoKQogICAgCXdoZW4gJ1R1YWxvXE9mZmljZVxPbmxpbmVWb3RlXFN0YXRlc1xMb2dp
bicKICAgICAgICAJaW5jbHVkZSBwYWdlLWxvZ2luCiAgICAJd2hlbiAnVHVhbG9cT2ZmaWNlXE9u
bGluZVZvdGVcU3RhdGVzXExlZ2l0aW1hdGlvbicKICAgICAgICAJaW5jbHVkZSBwYWdlLWxlZ2l0
aW1hdGlvbgogICAgICAgIHdoZW4gJ1R1YWxvXE9mZmljZVxPbmxpbmVWb3RlXFN0YXRlc1xMb2dv
dXQnCiAgICAgICAgCWluY2x1ZGUgcGFnZS1sb2dvdXQKICAgICAgICB3aGVuICdUdWFsb1xPZmZp
Y2VcT25saW5lVm90ZVxTdGF0ZXNcQ2hvb3NlQmFsbG90cGFwZXInCiAgICAgICAgCWluY2x1ZGUg
cGFnZS1jaG9vc2ViYWxsb3RwYXBlcgogICAgICAgIHdoZW4gJ1R1YWxvXE9mZmljZVxPbmxpbmVW
b3RlXFN0YXRlc1xCYWxsb3RwYXBlcicKICAgICAgICAJaW5jbHVkZSBwYWdlLWJhbGxvdHBhcGVy
CiAgICAgICAgd2hlbiAnVHVhbG9cT2ZmaWNlXE9ubGluZVZvdGVcU3RhdGVzXEJhbGxvdHBhcGVy
T3ZlcnZpZXcnCiAgICAgICAgCWluY2x1ZGUgcGFnZS1vdmVydmlldwogICAgICAgIHdoZW4gJ1R1
YWxvXE9mZmljZVxPbmxpbmVWb3RlXFN0YXRlc1xTYXZlQ29tcGxldGVkQ2hvb3NlQmFsbG90cGFw
ZXInCiAgICAgICAgCWluY2x1ZGUgcGFnZS1zYXZlZC1jaG9vc2ViYWxsb3RwYXBlcgogICAgICAg
ICAgICBpbmNsdWRlIHBhZ2UtY2hvb3NlYmFsbG90cGFwZXIKICAgICAgICB3aGVuICdUdWFsb1xP
ZmZpY2VcT25saW5lVm90ZVxTdGF0ZXNcTG9naW5BbGxyZWFkeVZvdGVkRXJyb3InCiAgICAgICAg
CS12YXIgbXNnID0gIkbDvHIgZGllc2VuIFN0aW1temV0dGVsIHd1cmRlIGJlcmVpdHMgZ2V3w6Ro
bHQuIgogICAgICAgICAgICBpbmNsdWRlIHBhZ2UtZXJyb3IKICAgICAgICB3aGVuICdUdWFsb1xP
ZmZpY2VcT25saW5lVm90ZVxTdGF0ZXNcU2F2ZUNvbXBsZXRlZCcKICAgICAgICAJaW5jbHVkZSBw
YWdlLXNhdmVkCiAgICAgICAgd2hlbiAnVHVhbG9cT2ZmaWNlXE9ubGluZVZvdGVcU3RhdGVzXEVy
cm9yJwogICAgICAgIAlpbmNsdWRlIHBhZ2UtZXJyb3IKICAgICAgICB3aGVuICdUdWFsb1xPZmZp
Y2VcT25saW5lVm90ZVxTdGF0ZXNcQmFsbG90UGFwZXJBbGxyZWFkeVZvdGVkRXJyb3InCiAgICAg
ICAgCS12YXIgbXNnID0gIkbDvHIgZGllc2VuIFN0aW1temV0dGVsIHd1cmRlIGJlcmVpdHMgZ2V3
w6RobHQuIgogICAgICAgICAgICBpbmNsdWRlIHBhZ2UtZXJyb3IKICAgICAgICB3aGVuICdUdWFs
b1xPZmZpY2VcT25saW5lVm90ZVxTdGF0ZXNcU2Vzc2lvbkludmFsaWRFcnJvcicKICAgICAgICAJ
LXZhciBtc2cgPSAiSWhyZSBTaXR6dW5nIGlzdCBhYmdlbGF1ZmVuLiIKICAgICAgICAgICAgaW5j
bHVkZSBwYWdlLWVycm9yCiAgICAgICAgd2hlbiAnVHVhbG9cT2ZmaWNlXE9ubGluZVZvdGVcU3Rh
dGVzXFNlc3Npb25CYWxsb3RwYXBlclNhdmVFcnJvcicKICAgICAgICAJLXZhciBtc2cgPSAiRXMg
Z2lidCBiZXJlaXRzIGVpbmUgd2VpdGVyZSBBbm1lbGR1bmcuIgogICAgICAgICAgICBpbmNsdWRl
IHBhZ2UtZXJyb3IKICAgICAgICBkZWZhdWx0CiAgICAgICAgCWluY2x1ZGUgcGFnZS1tYWludGVu
YW5jZQogICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgIA==') );
 insert ignore into ds_pug_templates (name,id,note,template) values ('page-ballotpaper','page-ballotpaper',from_base64('cGFnZS1iYWxsb3RwYXBlcg=='),from_base64( 'LSB2YXIgZGlzYWJsZWQ9dHJ1ZQotIHZhciBiYWNrZ3JvdW5kX2NvbG9yPSJ2YXIoLS1icy1saWdo
dC10ZXh0KSIKaWYgY21zLndtcy5nZXROZXh0U3RhdGUoKT09J1R1YWxvXE9mZmljZVxPbmxpbmVW
b3RlXFN0YXRlc1xCYWxsb3RwYXBlcicKICAgIC0gZGlzYWJsZWQ9ZmFsc2UKICAgIC0gYmFja2dy
b3VuZF9jb2xvcj1jbXMuYmFsbG90cGFwZXIuZmFyYmUKCmZvcm0ucGFnZS1iYWxsb3RwYXBlci5j
b250YWluZXItZmx1aWQobWV0aG9kPSJwb3N0IikKCWRpdi5jb250YWluZXIKICAgIAlpbmNsdWRl
IHBhZ2UtYmFsbG90cGFwZXItdGl0bGUKCQlkaXYucm93CgkJCWluY2x1ZGUgcGFnZS1iYWxsb3Rw
YXBlci10YWJsZQogICAgICAgIGluY2x1ZGUgcGFnZS1iYWxsb3RwYXBlci1mb290ZXIKCQlpbmNs
dWRlIHBhZ2UtYmFsbG90cGFwZXItYnV0dG9ucwoK') );
 insert ignore into ds_pug_templates (name,id,note,template) values ('page-ballotpaper-buttons','page-ballotpaper-buttons',from_base64('cGFnZS1iYWxsb3RwYXBlci1idXR0b25z'),from_base64( 'ZGl2LnJvdy5idXR0b25zCglkaXYuY29sCgkgICAgaW5wdXQodHlwZT0iaGlkZGVuIixuYW1lPSJz
ZW5kIix2YWx1ZT0iMSIpCiAgICAJYnV0dG9uLmJ0bi5idG4tc3VjY2Vzcyh0eXBlPSJzdWJtaXQi
KSAhe2Ntcy50eHQoJ2JhbGxvdHBhcGVyX3N1Ym1pdF9idXR0b24nKX0K') );
 insert ignore into ds_pug_templates (name,id,note,template) values ('page-ballotpaper-footer','page-ballotpaper-footer',from_base64('cGFnZS1iYWxsb3RwYXBlci1mb290ZXI='),from_base64( 'ZGl2LnJvdwoJLSB2YXIgdGV4dCA9IGNtcy5tYXJrZG93bihjbXMudHh0KCdzdWJtaXRfZmlyc3Qn
KSkKCWRpdi5jb2wgIXt0ZXh0fQ==') );
 insert ignore into ds_pug_templates (name,id,note,template) values ('page-ballotpaper-table','page-ballotpaper-table',from_base64('cGFnZS1iYWxsb3RwYXBlci10YWJsZQ=='),from_base64( 'dGFibGUudGFibGUudGFibGUtc3RyaXBlZAoJdGhlYWQKCQl0cgoJCQl0aChzY29wZT0iY29sIikg
Jm5ic3A7CgkJCXRoLmNoZWNrLmFsaWduLW1pZGRsZShzY29wZT0iY29sIixzdHlsZT0iYmFja2dy
b3VuZC1jb2xvcjoiK2JhY2tncm91bmRfY29sb3IpCiAgICAgICAgICAgIAkrYmFsbG90cGFwZXJt
YXgoY21zLmJhbGxvdHBhcGVyKQoJdGJvZHkKCQllYWNoIGJhbGxvdHBhcGVyX2dyb3VwIGluIGNt
cy5iYWxsb3RwYXBlcl9ncm91cHMKCQkJZWFjaCBjYW5kaWRhdGUgaW4gYmFsbG90cGFwZXJfZ3Jv
dXAuY2FuZGlkYXRlcwoJCQkJdHIKCQkJCQl0ZChzY29wZT0icm93IikKICAgICAgICAgICAgICAg
ICAgICAJaW5jbHVkZSBwYWdlLWJhbGxvdHBhcGVyLXRhYmxlLWNvbnRlbnQKCQkJCQl0ZC5hbGln
bi1taWRkbGUoc2NvcGU9InJvdyIsc3R5bGU9ImJhY2tncm91bmQtY29sb3I6IitiYWNrZ3JvdW5k
X2NvbG9yKQogICAgICAgICAgICAgICAgICAgICAgICArY2hlY2tib3goCiAgICAgICAgICAgICAg
ICAgICAgICAgIAknQicrY21zLndtcy52b3RlcigpLmJhbGxvdHBhcGVyKCkuZ2V0TWFwSGFzaChj
YW5kaWRhdGUuaWQpLAogICAgICAgICAgICAgICAgICAgICAgICAgICAgJ2NhbmRpZGF0ZVtdJywK
ICAgICAgICAgICAgICAgICAgICAgICAgICAgIGNtcy53bXMudm90ZXIoKS5iYWxsb3RwYXBlcigp
LmdldE1hcEhhc2goY2FuZGlkYXRlLmlkKSwKICAgICAgICAgICAgICAgICAgICAgICAgICAgIGNt
cy53bXMudm90ZXIoKS5iYWxsb3RwYXBlcigpLmlzQ2hlY2tlZChjYW5kaWRhdGUuaWQpLAogICAg
ICAgICAgICAgICAgICAgICAgICAgICAgZGlzYWJsZWQKICAgICAgICAgICAgICAgICAgICAgICAg
KQo=') );
 insert ignore into ds_pug_templates (name,id,note,template) values ('page-ballotpaper-table-content','page-ballotpaper-table-content',from_base64('cGFnZS1iYWxsb3RwYXBlci10YWJsZS1jb250ZW50'),from_base64( 'ZWFjaCByb3cgaW4gY21zLnJvd3MKCWRpdihjbGFzcz0icm93Iityb3cucHJlZml4KyIgIityb3cu
cm93X25hbWUpCgkJZWFjaCBjb2wgaW4ganNvbl9kZWNvZGUocm93LmNvbHVtbnMsdHJ1ZSkKCQkJ
ZGl2KGNsYXNzPSJjb2wiK2NvbC5wcmVmaXgrIiAiK2NvbC5jb2x1bW5fbmFtZSkKCQkJCWVhY2gg
ZmllbGQgaW4gY29sLmRlZmluaXRpb24KCQkJCQlpZiBmaWVsZC5odG1sdGFnPT0naW1nJwoJCQkJ
CQlpbWcoCgkJCQkJCQljbGFzcz1maWVsZC5jb2x1bW5fZmllbGQKCQkJCQkJCXN0eWxlPSJib3Jk
ZXItcmFkaXVzOiAxMHB4OyIKCQkJCQkJCXNyYz0iL2ltYWdlcy9wb3J0cmFpdC8iK2NhbmRpZGF0
ZVtmaWVsZC5jb2x1bW5fZmllbGRdKyIucG5nIgoJCQkJCQkpCgkJCQkJZWxzZQoJCQkJCQlwKGNs
YXNzPWZpZWxkLmNvbHVtbl9maWVsZCkgIXtjYW5kaWRhdGVbZmllbGQuY29sdW1uX2ZpZWxkXX0=') );
 insert ignore into ds_pug_templates (name,id,note,template) values ('page-ballotpaper-title','page-ballotpaper-title',from_base64('cGFnZS1iYWxsb3RwYXBlci10aXRsZQ=='),from_base64( 'ZGl2LnJvdwoJZGl2LmNvbAogICAgCS8vIC50ZXh0LWNvbnRvdXIKICAgIAloNChzdHlsZT0iY29s
b3I6IitiYWNrZ3JvdW5kX2NvbG9yKSAhe2Ntcy5iYWxsb3RwYXBlci5uYW1lfQoJCQ==') );
 insert ignore into ds_pug_templates (name,id,note,template) values ('page-chooseballotpaper','page-chooseballotpaper',from_base64('cGFnZS1jaG9vc2ViYWxsb3RwYXBlcg=='),from_base64( 'LXZhciBhdmFpbGFibGVCYWxsb3RwYXBlcnMgPSBjbXMud21zLnZvdGVyKCkuYXZhaWxhYmxlQmFs
bG90cGFwZXJzKCkKLXZhciBncm91cHMgPSBjbXMud21zLnZvdGVyKCkuYXZhaWxhYmxlQmFsbG90
cGFwZXJHcm91cHMoKQotdmFyIGxhc3RJbmRleD0tMQpkaXYucGFnZS1jaG9vc2ViYWxsb3RwYXBl
ci5jb250YWluZXItZmx1aWQKCWRpdi5jb250YWluZXIKCQlkaXYucm93CgkJCWRpdi5jb2wgQml0
dGUgd8OkaGxlbiBTaWUgZWluZW4gU3RpbW16ZXR0ZWwgYXVzLCBmw7xyIHdlbGNoZW4gU2llIGpl
dHp0IGFic3RpbW1lbiBtw7ZjaHRlbi4KZGl2LnBhZ2UtY2hvb3NlYmFsbG90cGFwZXIuY29udGFp
bmVyLWZsdWlkCglkaXYuY29udGFpbmVyCgkJZWFjaCBncm91cCBpbiBncm91cHMKCQkJZGl2LnBh
Z2UtY2hvb3NlYmFsbG90cGFwZXIucm93CgkJCQlkaXYuY29sLWF1dG8KCQkJCQkvLyAudGV4dC1j
b250b3VyCgkJCQkJaDQoc3R5bGU9ImNvbG9yOiIrZ3JvdXAuY29sb3IrIjsiKSAhe2dyb3VwLm5h
bWV9CgkJCQlkaXYuY29sLnRleHQtZW5kCgkJCQkJc3BhbiAoIXtncm91cC5jb3VudH0pCgkJCQkJ
CgkJCWVhY2ggYnAsaW5kZXggaW4gYXZhaWxhYmxlQmFsbG90cGFwZXJzCgkJCQktIHZhciBkYXRh
ID0gYnAuZ2V0Vm90ZXJEYXRhKCk7CgkJCQlpZiBncm91cC5pZCA9PSBicC5nZXRCYWxsb3RwYXBl
cklkKCkKCQkJCQktIGxhc3RJbmRleD1pbmRleDsKCQkJCQlkaXYucm93CgkJCQkJCWRpdi5jb2wt
MQoJCQkJCQlkaXYuY29sCgkJCQkJCQlhKGhyZWY9Ij9iYWxsb3RwYXBlckluZGV4PSIraW5kZXgp
ICF7ZGF0YS5wb3N0X25hbWUyfQoJCQkJCQlkaXYuY29sLTEKCQkJaWYgZ3JvdXAuY291bnQ+MSAg
ICAgICAgICAgICAgICAgICAgICAgIAoJCQkJZGl2LnJvdwoJCQkJCWRpdi5jb2wtMSAmbmJzcDsK
CQkJCQlkaXYuY29sLWF1dG8KCQkJCQkJc3BhbiBVbSBmw7xyIGFsbGUgVW50ZXJuZWhtZW4gbWl0
IGRlbSBTdGltbXpldHRlbCAiIXtncm91cC5uYW1lfSIgaWRlbnRpc2NoIGFienVzdGltbWVuLCBr
bGlja2VuIFNpZSBiaXR0ZSAKCQkJCQkJYShocmVmPSI/Z3JvdXBlZD0xJmJhbGxvdHBhcGVySW5k
ZXg9IitsYXN0SW5kZXgpIGhpZXIgICAgICAgICAgICAKCQkJCQkJc3BhbiAuCgkvLyBkaXYuY29u
dGFpbmVyCgkJZWFjaCBicCBpbiBhdmFpbGFibGVCYWxsb3RwYXBlcnMKCQkJLSB2YXIgZGF0YSA9
IGJwLmdldFZvdGVyRGF0YSgpOwoJCQlkaXYucm93CgkJCQlkaXYuY29sIAoJCQkJCWEoaHJlZj0i
P2JhbGxvdHBhcGVySW5kZXg9IitpbmRleCkKCQkJCQkJaDQgIXticC5nZXRCYWxsb3RwYXBlck5h
bWUoKX0KCQkJCQkJcCAhe2RhdGEucG9zdF9uYW1lMn0KCQkJCQktIGluZGV4ID0gaW5kZXggKzEK
Cg==') );
 insert ignore into ds_pug_templates (name,id,note,template) values ('page-debug','page-debug',from_base64('cGFnZS1kZWJ1Zw=='),from_base64( 'ZGl2LnBhZ2UtZGVidWcuY29udGFpbmVyLWZsdWlkLmFsZXJ0LmFsZXJ0LWRhbmdlcihyb2xlPSJh
bGVydCIpCglkaXYuY29udGFpbmVyCgkJZGl2LnJvdwoJCQlkaXYuY29sLnRleHQtdHJ1bmNhdGUg
TmV4dFN0YXRlICF7Y21zLndtcy5nZXROZXh0U3RhdGUoKX0KCQlkaXYucm93CgkJCWRpdi5jb2wu
dGV4dC10cnVuY2F0ZSBDdXJyZW50U3RhdGUgIXtjbXMud21zLmdldEN1cnJlbnRTdGF0ZSgpfQog
ICAgICAgIGRpdi5yb3cKICAgICAgICAJZGl2LmNvbC50ZXh0LXRydW5jYXRlIFByZXZTdGF0ZSAh
e2Ntcy53bXMuZ2V0UHJldlN0YXRlKCl9Cg==') );
 insert ignore into ds_pug_templates (name,id,note,template) values ('page-documentation','page-documentation',from_base64('cGFnZS1kb2N1bWVudGF0aW9u'),from_base64( 'ZXh0ZW5kcyBwYWdlLW1haW4KaW5jbHVkZSBwYWdlLW1peGluLWNoZWNrYm94CmluY2x1ZGUgcGFn
ZS1taXhpbi1iYWxsb3RwYXBlci1tYXgKCmJsb2NrIGNvbnRlbnQKICAgIGRpdi5jb250YWluZXIt
Zmx1aWQKCSAgICBkaXYuY29udGFpbmVyCiAgICAJICAgIGRpdi5yb3cKICAgICAgICAJICAgIGRp
di5jb2wgIXtjbXMubWFya2Rvd24oY21zLnR4dCgnZG9jdW1lbnRhdGlvbl9ibG9ja18wJykpfQog
ICAgCSAgICBkaXYucm93CiAgICAgICAgCSAgICBkaXYuY29sICF7Y21zLm1hcmtkb3duKGNtcy50
eHQoJ2RvY3VtZW50YXRpb25fYmxvY2tfMScpKX0KICAgIAkgICAgZGl2LnJvdwogICAgICAgIAkg
ICAgZGl2LmNvbCAhe2Ntcy5tYXJrZG93bihjbXMudHh0KCdkb2N1bWVudGF0aW9uX2Jsb2NrXzIn
KSl9CiAgICAJICAgIGRpdi5yb3cKICAgICAgICAJICAgIGRpdi5jb2wgIXtjbXMubWFya2Rvd24o
Y21zLnR4dCgnZG9jdW1lbnRhdGlvbl9ibG9ja18zJykpfQogICAgCSAgICBkaXYucm93CiAgICAg
ICAgCSAgICBkaXYuY29sICF7Y21zLm1hcmtkb3duKGNtcy50eHQoJ2RvY3VtZW50YXRpb25fYmxv
Y2tfNCcpKX0KICAgIAkgICAgZGl2LnJvdwogICAgICAgIAkgICAgZGl2LmNvbCAhe2Ntcy5tYXJr
ZG93bihjbXMudHh0KCdkb2N1bWVudGF0aW9uX2Jsb2NrXzUnKSl9CiAgICAJICAgIGRpdi5yb3cK
ICAgICAgICAJICAgIGRpdi5jb2wgIXtjbXMubWFya2Rvd24oY21zLnR4dCgnZG9jdW1lbnRhdGlv
bl9ibG9ja182JykpfQog') );
 insert ignore into ds_pug_templates (name,id,note,template) values ('page-error','page-error',from_base64('cGFnZS1lcnJvcg=='),from_base64( 'ZGl2LnBhZ2UtZXJyb3IuY29udGFpbmVyLWZsdWlkCglkaXYuY29udGFpbmVyCgkJZGl2LnJvdwoJ
CQlkaXYuY29sIEVzIGlzdCBlaW4gRmVobGVyIHBhc3NpZXJ0IAoJCWRpdi5yb3cKCQkJZGl2LmNv
bCAhe21zZ30K') );
 insert ignore into ds_pug_templates (name,id,note,template) values ('page-footer','page-footer',from_base64('cGFnZS1mb290ZXI='),from_base64( 'Zm9vdGVyLnBhZ2UtZm9vdGVyLmNvbnRhaW5lci1mbHVpZAoJZGl2LmNvbnRhaW5lcgoJCWRpdi5y
b3cKICAgICAgICAgICAgZGl2LmNvbC1tZC00CiAgICAgICAgICAgIAl1bC5taWQtbGlua2xpc3Qo
c3R5bGU9Imxpc3Qtc3R5bGUtdHlwZTogbm9uZTsgbWFyZ2luOiAwOyAgcGFkZGluZzogMDsiKQoJ
ICAgICAgICAgICAgCWVhY2ggcmVjb3JkIGluIGNtcy5saW5rcwogICAgICAgICAgICAgICAgICAg
IAlpZiByZWNvcmQuZm9vdGVyMT09MQoJICAgIAkgICAgICAgICAgICAJbGkuZm9vdGVyLW5hdi1p
dGVtCiAgICAJICAgICAgICAgICAgICAgICAgICAJYShocmVmPXJlY29yZC51cmwsdGFyZ2V0PXJl
Y29yZC52YXJ0YXJnZXQscmVsPSJub29wZW5lciIpPXJlY29yZC50aXRsZQogICAgICAgICAgICBk
aXYuY29sLW1kLTQKICAgICAgICAgICAgCXVsLm1pZC1saW5rbGlzdChzdHlsZT0ibGlzdC1zdHls
ZS10eXBlOiBub25lOyBtYXJnaW46IDA7ICBwYWRkaW5nOiAwOyIpCgkgICAgICAgICAgICAJZWFj
aCByZWNvcmQgaW4gY21zLmxpbmtzCiAgICAgICAgICAgICAgICAgICAgCWlmIHJlY29yZC5mb290
ZXIyPT0xCgkgICAgCSAgICAgICAgICAgIAlsaS5mb290ZXItbmF2LWl0ZW0KICAgIAkgICAgICAg
ICAgICAgICAgICAgIAlhKGhyZWY9cmVjb3JkLnVybCx0YXJnZXQ9cmVjb3JkLnZhcnRhcmdldCxy
ZWw9Im5vb3BlbmVyIik9cmVjb3JkLnRpdGxlCiAgICAgICAgICAgIAogICAgICAgIAlkaXYuY29s
LW1kLTQKICAgICAgICAgICAgCXVsLm1pZC1saW5rbGlzdChzdHlsZT0ibGlzdC1zdHlsZS10eXBl
OiBub25lOyBtYXJnaW46IDA7ICBwYWRkaW5nOiAwOyIpCgkgICAgICAgICAgICAJZWFjaCByZWNv
cmQgaW4gY21zLmxpbmtzCiAgICAgICAgICAgICAgICAgICAgCWlmIHJlY29yZC5mb290ZXIzPT0x
CgkgICAgCSAgICAgICAgICAgIAlsaS5mb290ZXItbmF2LWl0ZW0KICAgIAkgICAgICAgICAgICAg
ICAgICAgIAlhKGhyZWY9cmVjb3JkLnVybCx0YXJnZXQ9cmVjb3JkLnZhcnRhcmdldCxyZWw9Im5v
b3BlbmVyIik9cmVjb3JkLnRpdGxlCiAgICAJZGl2LnJvdwogICAgICAgIAlkaXYuY29sLnRleHQt
Y2VudGVyCiAgICAgICAgICAgICAgc3Bhbi5icC1mcy1zbWFsbCDCqSAhe2Ntcy50eHQoJ2NvcHly
aWdodCcpfSAK') );
 insert ignore into ds_pug_templates (name,id,note,template) values ('page-header','page-header',from_base64('cGFnZS1oZWFkZXI='),from_base64( 'aGVhZGVyLnBhZ2UtaGVhZGVyLmNvbnRhaW5lci1mbHVpZAoJZGl2LmNvbnRhaW5lcgoJCWRpdi5y
b3cKICAgICAgICAgICAgZGl2LmNvbC1tZC00LnRleHQtc3RhcnQKICAgICAgICAgICAgICAgIGEo
aHJlZj1jbXMudHh0KCdpaGtfbG9nb19saW5rJyksdGFyZ2V0PSJfYmxhbmsiLHJlbD0ibm9vcGVu
ZXIiKQogICAgICAgICAgICAgICAgCWltZyhzcmM9Ii9pbWFnZXMvTG9nb19JSEstS2llbC5zdmci
LCBzdHlsZT0iaGVpZ2h0OiAyLjBjbSIpCgkJCWRpdi5jb2wtbWQtNC50ZXh0LWNlbnRlcgogICAg
ICAgICAgICAgICAgYS5kLW5vbmUuZC1tZC1pbmxpbmUoaHJlZj1jbXMudHh0KCd3YWhsX2xvZ29f
bGluaycpLHRhcmdldD0iX2JsYW5rIixyZWw9Im5vb3BlbmVyIikKICAgICAgICAgICAgICAgIAlp
bWcoc3JjPSIvaW1hZ2VzL1dhaGxsb2dvLU11c3Rlci5zdmciKQogICAgICAgICAgICBkaXYuY29s
LW1kLTQudGV4dC1lbmQKICAgICAgICAgICAgCWRpdi5yb3cKICAgICAgICAgICAgICAgIAlkaXYu
Y29sCgkJCQkJCWEoaHJlZj0idGVsOiIrY21zLnR4dCgnaGVhZGVyX3RlbGVmb25fbGluaycpKQog
ICAgICAgICAgICAgICAgICAgIAkJaS5mYXIuZmEtcGhvbmUtYWx0CiAgICAgICAgICAgICAgICAg
ICAgCQkJc3Bhbi5kLW5vbmUuZC1zbS1pbmxpbmUgJm5ic3A7Jm5ic3A7IXtjbXMudHh0KCdoZWFk
ZXJfdGVsZWZvbl90ZXh0Jyl9IAogICAgICAgICAgICAJLWlmIChjbXMud21zLnZvdGVyKCkuaXNM
b2dnZWRJbigpID09IHRydWUgKQogICAgICAgICAgICAJCWRpdi5yb3cKICAgICAgICAgICAgICAg
IAkJZGl2LmNvbAogICAgICAgICAgICAgICAgICAgICAgICAJYS5idG4uYnRuLXByaW1hcnkoaHJl
Zj0iLi8/bG9nb3V0PTEiLHJlbD0ibm9vcGVuZXIiICkgIXtjbXMubWQoJ2J1dHRvbl9sb2dvdXQn
KX0KZGl2LnBhZ2UtY2xhaW0uY29udGFpbmVyLWZsdWlkLmJnLXByaW1hcnkKCWRpdi5jb2wucGFn
ZS1jbGFpbQoJCXNwYW4gIXtjbXMudHh0KCdsb2dpbmZvcm1fbGlnaHRfbGluZScpfSAKICAgICAg
IAlpZiBjbXMudHh0KCdsb2dpbmZvcm1fZGFya19saW5lJykubGVuZ3RoID4gMQoJCQlicgoJCQlz
cGFuKHN0eWxlPSJmb250LXdlaWdodDogTGlnaHRlc3Q7IikgIXtjbXMudHh0KCdsb2dpbmZvcm1f
ZGFya19saW5lJyl9IA==') );
 insert ignore into ds_pug_templates (name,id,note,template) values ('page-legitimation','page-legitimation',from_base64('cGFnZS1sZWdpdGltYXRpb24='),from_base64( 'ZGl2LnBhZ2UtbGVnaXRpbWF0aW9uLmNvbnRhaW5lci1mbHVpZAoJZGl2LmNvbnRhaW5lcgoJCWRp
di5yb3cKCQkJZGl2LmNvbCAhe2Ntcy5tYXJrZG93bihjbXMudHh0KCdsZWdpdGltYXRpb24nKSl9
CmRpdi5jb250YWluZXItZmx1aWQKICAgIGRpdi5jb250YWluZXIKICAgIAlkaXYucm93CiAgICAg
ICAgCWZvcm0uY29sKG1ldGhvZD0icG9zdCIsYWN0aW9uPSIuLyIpCiAgICAgICAgICAgIAlpbnB1
dCgKICAgICAgICAgIAkJCXR5cGU9ImhpZGRlbiIsCgkJCSAgICAgICAgbmFtZT0ibG9nb3V0IiwK
CQkJICAgICAgICB2YWx1ZT0xCgkJCSAgICApCiAgICAgICAgICAgICAgICBidXR0b24uYnRuLmJ0
bi13YXJuaW5nICF7Y21zLm1hcmtkb3duKGNtcy50eHQoJ2xlZ2l0aW1hdGlvbl9ubycpKX0KICAg
ICAgICAJZm9ybS5jb2wobWV0aG9kPSJwb3N0IixhY3Rpb249Ii4vIikKICAgICAgICAgICAgCWlu
cHV0KAogICAgICAgICAgCQkJdHlwZT0iaGlkZGVuIiwKCQkJICAgICAgICBuYW1lPSJsZWdpdGlt
YXRpb24iLAoJCQkgICAgICAgIHZhbHVlPWNtcy5sZWdpdGltYXRpb25fdXVpZAoJCQkgICAgKQog
ICAgICAgICAgICAgICAgaW5wdXQoCiAgICAgICAgICAJCQl0eXBlPSJoaWRkZW4iLAoJCQkgICAg
ICAgIG5hbWU9ImxlZ2l0aW1hdGlvbl9jb25maXJtZWQiLAoJCQkgICAgICAgIHZhbHVlPTEKCQkJ
ICAgICkKICAgICAgICAgICAgICAgIGJ1dHRvbi5idG4uYnRuLXN1Y2Nlc3MgIXtjbXMubWFya2Rv
d24oY21zLnR4dCgnbGVnaXRpbWF0aW9uX3llcycpKX0KaW5jbHVkZSBwYWdlLWxlZ2l0aW1hdGlv
bi1zdWJ0ZXh0Cg==') );
 insert ignore into ds_pug_templates (name,id,note,template) values ('page-legitimation-subtext','page-legitimation-subtext',from_base64('cGFnZS1sZWdpdGltYXRpb24tc3VidGV4dA=='),from_base64( 'ZGl2LmNvbnRhaW5lci1mbHVpZC5wYWdlLWxlZ2l0aW1hdGlvbi1zdWJ0ZXh0CglkaXYuY29udGFp
bmVyCgkJZGl2LnJvdwogICAgICAgIAlkaXYuY29sLmxlZ2l0aW1hdGlvbiAhe2Ntcy5tYXJrZG93
bihjbXMudHh0KCdsZWdpdGltYXRpb25fc3VidGV4dCcpKX0K') );
 insert ignore into ds_pug_templates (name,id,note,template) values ('page-login','page-login',from_base64('cGFnZS1sb2dpbg=='),from_base64( 'Zm9ybS5wYWdlLWxvZ2luLmNvbnRhaW5lci1mbHVpZChtZXRob2Q9InBvc3QiLGFjdGlvbj0iLi8i
KQoJZGl2LmNvbnRhaW5lcgoJCWRpdi5yb3cuYWxlcnQuYWxlcnQtcHJpbWFyeQogICAgCQlkaXYu
Y29sICF7Y21zLm1hcmtkb3duKGNtcy50eHQoJ2xvZ2luZm9ybV93ZWxsY29tZV90ZXh0JykpfQoJ
CWRpdi5yb3cKICAgIAkJZGl2LmNvbCAhe2Ntcy5tYXJrZG93bihjbXMudHh0KCdsb2dpbmZvcm1f
c2VjdXJpdHknKSl9IAoJCWRpdi5yb3cKICAgIAkJZGl2LmNvbAogICAgICAgIAkJaW5jbHVkZSBw
YWdlLWxvZ2luLWZvcm0K') );
 insert ignore into ds_pug_templates (name,id,note,template) values ('page-login-form','page-login-form',from_base64('cGFnZS1sb2dpbi1mb3Jt'),from_base64( 'LXZhciBwYXR0ZXJuPSJbQUJDREVGR0hKS0xNTlBSU1RVVlhZWmFiY2RlZmdoaWprbXBzdHV2eHl6
MDEyMzQ1Njc4OV17OH0iCmlucHV0LmhpbnQtY2lyY2xlLWNoZWNrYm94KAogIGlkPSdsb2dpbnRy
aWdnZXInCiAgbmFtZT0nYWNjZXB0JwogIHR5cGU9ImNoZWNrYm94IgogIGNoZWNrZWQ9ZmFsc2UK
ICBkaXNhYmxlZD1mYWxzZQogIHJlcXVpcmVkPXRydWUKKQpsYWJlbC5jb250YWluZXIoIGZvcj0n
bG9naW50cmlnZ2VyJyApCglkaXYucm93CgkJZGl2LmNvbC1hdXRvCiAgICAJCWkuZmFyLmZhLXRp
bWVzCgkJZGl2LmNvbCAhe2Ntcy5tYXJrZG93bihjbXMudHh0KCdsb2dpbmZvcm1fYm94aGlud2Vp
cycpKX0KICAgIAkKZGl2LmZvcm1ib3gKICAgIGRpdi5mb3JtLWdyb3VwCiAgICAgICAgbGFiZWwo
Zm9yPSJwMSIpIExvZ2luCiAgICAgICAgaW5wdXQuZm9ybS1jb250cm9sLmNvbCgKICAgICAgICAJ
dHlwZT0idGV4dCIsCiAgICAgICAgICAgIHBhdHRlcm49cGF0dGVybiwKICAgICAgICAgICAgcGxh
Y2Vob2xkZXI9IkxvZ2luIiwKICAgICAgICAgICAgbWF4bGVuZ3RoPSI4IiwKICAgICAgICAgICAg
bmFtZT1jbXMud21zLnVzZXJuYW1lZmllbGQoKSwKICAgICAgICAgICAgaWQ9InAxIiwKICAgICAg
ICAgICAgcmVxdWlyZWQ9InRydWUiLAogICAgICAgICAgICB0aXRsZT1jbXMudHh0KCdmb3JtX2lu
cHV0X3RpdGxlJyksCiAgICAgICAgICAgIHZhbHVlPWNtcy5wMQogICAgICAgICkKICAgIGRpdi5m
b3JtLWdyb3VwKHN0eWxlPSJtYXJnaW4tYm90dG9tOiAxMHB4OyIpCiAgICAgICAgbGFiZWwoZm9y
PSJwMiIpIFBhc3N3b3J0CiAgICAgICAgaW5wdXQuZm9ybS1jb250cm9sLmNvbCgKICAgICAgICAJ
dHlwZT0icGFzc3dvcmQiLAogICAgICAgICAgICBwYXR0ZXJuPXBhdHRlcm4sCiAgICAgICAgICAg
IHBsYWNlaG9sZGVyPSJQYXNzd29ydCIsCiAgICAgICAgICAgIG1heGxlbmd0aD0iOCIsCiAgICAg
ICAgICAgIG5hbWU9Y21zLndtcy5wYXNzd29yZGZpZWxkKCksCiAgICAgICAgICAgIGlkPSJwMiIs
CiAgICAgICAgICAgIHJlcXVpcmVkPSJ0cnVlIiwKICAgICAgICAgICAgdGl0bGU9Y21zLnR4dCgn
Zm9ybV9pbnB1dF90aXRsZScpLAogICAgICAgICAgICB2YWx1ZT1jbXMucDIKICAgICAgICApCgog
ICAgYnIKICAgIGRpdiNjb29raWVEaXYucm93KHN0eWxlPSJkaXNwbGF5Om5vbmU7IikKICAgICAg
ICBkaXYuY29sICF7Y21zLm1hcmtkb3duKGNtcy50eHQoJ2Nvb2tpZV90ZXh0JykpfQogICAgCiAg
ICBkaXYucm93CiAgICAgICAgZGl2LmNvbAogICAgICAgICAgICBidXR0b24uYnRuLmJ0bi1zdWNj
ZXNzKHR5cGU9InN1Ym1pdCIpICF7Y21zLm1hcmtkb3duKGNtcy50eHQoJ2J1dHRvbl9sb2dpbicp
KX0=') );
 insert ignore into ds_pug_templates (name,id,note,template) values ('page-logout','page-logout',from_base64('cGFnZS1sb2dvdXQ='),from_base64( 'ZGl2LnBhZ2UtbG9nb3V0LmNvbnRhaW5lci1mbHVpZAoJZGl2LmNvbnRhaW5lcgoJCWRpdi5yb3cK
CQkJZGl2LmNvbCAhe2Ntcy5tZCgnYXNrbG9nb3V0X3RleHQnKX0KCQlkaXYucm93CgkJCWRpdi5j
b2wKICAgICAgICAgICAgCWEuYnRuLmJ0bi1pbmZvKAogICAgICAgICAgICAgICAgCWhyZWY9Ii4v
P2xvZ291dF9jb25maXJtZWQ9MSIsCiAgICAgICAgICAgICAgICAgICAgcmVsPSJub29wZW5lciIK
ICAgICAgICAgICAgICAgICkgIXtjbXMubWQoJ2Fza2xvZ291dF9idXR0b25fbG9nb3V0Jyl9CgkJ
CWRpdi5jb2wKICAgICAgICAgICAgCWEuYnRuLmJ0bi1pbmZvKAogICAgICAgICAgICAgICAgCWhy
ZWY9Ii4vP2xvZ291dF9jYW5jZWxlZD0xIiwKICAgICAgICAgICAgICAgICAgICByZWw9Im5vb3Bl
bmVyIgogICAgICAgICAgICAgICAgKSAhe2Ntcy5tZCgnYXNrbG9nb3V0X2J1dHRvbl9iYWNrJyl9
Cg==') );
 insert ignore into ds_pug_templates (name,id,note,template) values ('page-main','page-main',from_base64('cGFnZS1tYWlu'),from_base64( 'Lgpkb2N0eXBlIGh0bWwKaHRtbChsYW5nPSdkZScpCiAgICBoZWFkCiAgICAgICAgYmxvY2sgaGVh
ZAogICAgICAgICAgICBtZXRhKGNoYXJzZXQ9J3V0Zi04JykKCQkJbWV0YShuYW1lPSJmb3JtYXQt
ZGV0ZWN0aW9uIixjb250ZW50PSJ0ZWxlcGhvbmU9bm8iKQogICAgICAgICAgICBtZXRhKG5hbWU9
InZpZXdwb3J0Iixjb250ZW50PSJ3aWR0aD1kZXZpY2Utd2lkdGgsIGluaXRpYWwtc2NhbGU9MSwg
c2hyaW5rLXRvLWZpdD1ubyIpCiAgICAgICAgICAgIHRpdGxlICF7Y21zLnR4dCgnc2l0ZV90aXRs
ZScpfQoJCQlsaW5rKAogICAgICAgICAgICAJaHJlZj0iLi9ib290c3RyYXBidWlsZC9ib290c3Ry
YXAuY3NzIiAKICAgICAgICAgICAgICAgIHJlbD0ic3R5bGVzaGVldCIgCiAgICAgICAgICAgICAg
ICAKICAgICAgICAgICAgKQogICAgICAgICAgICBsaW5rKHJlbD0ic3R5bGVzaGVldCIsaHJlZj0i
L2ZvbnRhd2Vzb21lLXByby9jc3MvYWxsLmNzcyIpCiAgICAgICAgICAgIGxpbmsocmVsPSJzdHls
ZXNoZWV0IixocmVmPSIuL3BhZ2UuY3NzIikKICAgICAgICAgICAgc2NyaXB0KHR5cGU9InRleHQv
amF2YXNjcmlwdCIsc3JjPSIvanMvY29va2llLWNoZWNrLmpzIixkZWZlcikKCWJvZHkodGFiSW5k
ZXg9MCkKICAgIAlpbmNsdWRlIHBhZ2UtaGVhZGVyCiAgICAJYmxvY2sgY29udGVudAogICAgICAg
IGluY2x1ZGUgcGFnZS1kZWJ1ZwogICAgICAgIGluY2x1ZGUgcGFnZS1mb290ZXI=') );
 insert ignore into ds_pug_templates (name,id,note,template) values ('page-maintenance','page-maintenance',from_base64('cGFnZS1tYWludGVuYW5jZQ=='),from_base64( 'ZGl2LnBhZ2UtbWFpbnRlbmFuY2UuY29udGFpbmVyLWZsdWlkCglkaXYuY29udGFpbmVyCgkJZGl2
LnJvdwoJCQlkaXYuY29sICF7Y21zLm1kKCdtYWludGVuYW5jZScpfQo=') );
 insert ignore into ds_pug_templates (name,id,note,template) values ('page-mixin-ballotpaper-max','page-mixin-ballotpaper-max',from_base64('cGFnZS1taXhpbi1iYWxsb3RwYXBlci1tYXg='),from_base64( 'bWl4aW4gYmFsbG90cGFwZXJtYXgoYmFsbG90cGFwZXIpCgktIHZhciBrcmV1enRleHQ9J0tyZXV6
JwoJLSBpZiAoYmFsbG90cGFwZXIuc2l0emUgPiAxKQoJCS0ga3JldXp0ZXh0PSdLcmV1emUnCglk
aXYucm93LmFsaWduLW1pZGRsZS50ZXh0LWNlbnRlcgoJCXNwYW4gTWF4LgoJCWJyCgkJc3BhbiAh
e2JhbGxvdHBhcGVyLnNpdHplfQoJCWJyCgkJc3BhbiAhe2tyZXV6dGV4dH0K') );
 insert ignore into ds_pug_templates (name,id,note,template) values ('page-mixin-checkbox','page-mixin-checkbox',from_base64('cGFnZS1taXhpbi1jaGVja2JveA=='),from_base64( 'bWl4aW4gY2hlY2tib3goaWQsIG5hbWUsIHZhbHVlLCBjaGVja2VkLCBkaXNhYmxlZCwgcmVxdWly
ZWQsIGhpbnQpCiAgICBpbnB1dC5jaXJjbGUtY2hlY2tib3goCiAgICAgICAgaWQ9aWQKICAgICAg
ICBuYW1lPW5hbWUKICAgICAgICB2YWx1ZT12YWx1ZQogICAgICAgIHR5cGU9ImNoZWNrYm94Igog
ICAgICAgIGNoZWNrZWQ9Y2hlY2tlZAogICAgICAgIGRpc2FibGVkPWRpc2FibGVkCiAgICAgICAg
cmVxdWlyZWQ9cmVxdWlyZWQKICAgICkKICAgIGxhYmVsKCBmb3I9aWQgKQogICAgCWRpdgogICAg
ICAgIAlpLmZhci5mYS10aW1lcwogICAgICAgIHNwYW4gIXtoaW50fQo=') );
 insert ignore into ds_pug_templates (name,id,note,template) values ('page-overview','page-overview',from_base64('cGFnZS1vdmVydmlldw=='),from_base64( 'LSB2YXIga3JldXp0ZXh0PSdLcmV1eicKLSB2YXIgZGlzYWJsZWQ9dHJ1ZQotIHZhciBiYWNrZ3Jv
dW5kX2NvbG9yPSJ2YXIoLS1icy1saWdodC10ZXh0KSIKLSBpZiAoY21zLmJhbGxvdHBhcGVyLnNp
dHplID4gMSkKCS0ga3JldXp0ZXh0PSdLcmV1emUnCmZvcm0ucGFnZS1iYWxsb3RwYXBlci5jb250
YWluZXItZmx1aWQKCWRpdi5jb250YWluZXIKCQlpbmNsdWRlIHBhZ2UtYmFsbG90cGFwZXItdGl0
bGUKCQlkaXYucm93CgkJCWluY2x1ZGUgcGFnZS1iYWxsb3RwYXBlci10YWJsZQoJCWluY2x1ZGUg
cGFnZS1vdmVydmlldy1mb290ZXIKCQlpbmNsdWRlIHBhZ2Utb3ZlcnZpZXctYnV0dG9ucwoK') );
 insert ignore into ds_pug_templates (name,id,note,template) values ('page-overview-buttons','page-overview-buttons',from_base64('cGFnZS1vdmVydmlldy1idXR0b25z'),from_base64( 'ZGl2LnJvdy5idXR0b25zCglkaXYuY29sCiAgICAJYShocmVmPSIuLz9jb3JyZWN0PTEiKS5idG4u
YnRuLWRhbmdlciAhe2Ntcy5tZCgnYnV0dG9uX2NvcnJlY3RfdmFsaWQnKX0KCWRpdi5jb2wKICAg
IAlpZiBjbXMud21zLnZvdGVyKCkuYmFsbG90cGFwZXIoKS52YWxpZCgpID09PSB0cnVlCgkgICAg
CWEoaHJlZj0iLi8/c2F2ZT0xIikuYnRuLmJ0bi1zdWNjZXNzICF7Y21zLm1kKCdidXR0b25fZmlu
YWxfc2VuZCcpfQo=') );
 insert ignore into ds_pug_templates (name,id,note,template) values ('page-overview-footer','page-overview-footer',from_base64('cGFnZS1vdmVydmlldy1mb290ZXI='),from_base64( 'LSB2YXIgcGx1cmFsX3N1ZmZpeD0oIGNtcy53bXMudm90ZXIoKS5iYWxsb3RwYXBlcigpLm1heCgp
PjE/J19wbHVyYWwnOidfc2luZ3VsYXInICkKLSB2YXIgdGV4dF9rZXk9IiIKaWYgKGNtcy53bXMu
dm90ZXIoKS5iYWxsb3RwYXBlcigpLmNoZWNrY291bnQoKT09MCkKCS0gdGV4dF9rZXkgPSAnemVy
b3ZvdGUnCmVsc2UKCS0gdGV4dF9rZXkgPSAndmFsaWR2b3RlJwppZiBjbXMud21zLnZvdGVyKCku
YmFsbG90cGFwZXIoKS52YWxpZCgpICE9PSB0cnVlCgktIHRleHRfa2V5ID0gJ2ludmFsaWR2b3Rl
JwotIHRleHQgPSBjbXMubWQodGV4dF9rZXkrcGx1cmFsX3N1ZmZpeCkucmVwbGFjZSgiJW1heCIs
IGNtcy53bXMudm90ZXIoKS5iYWxsb3RwYXBlcigpLm1heCgpKS5yZXBsYWNlKCIlY2hlY2tjb3Vu
dCIsIGNtcy53bXMudm90ZXIoKS5iYWxsb3RwYXBlcigpLmNoZWNrY291bnQoKSkKZGl2LnJvdwoJ
ZGl2LmNvbCAhe3RleHR9') );
 insert ignore into ds_pug_templates (name,id,note,template) values ('page-saved','page-saved',from_base64('cGFnZS1zYXZlZA=='),from_base64( 'ZGl2LmNvbnRhaW5lci1mbHVpZAoJZGl2LmNvbnRhaW5lcgoJCWRpdi5yb3cKCQkJZGl2LmNvbCAh
e2Ntcy5tZCgnYmFsbG90cGFwZXJfc2F2ZWQnKX0KCQlkaXYucm93CgkJCWRpdi5jb2wgIXtjbXMu
bWQoJ2JhbGxvdHBhcGVyX3NhdmVkMicpfQo=') );
 insert ignore into ds_pug_templates (name,id,note,template) values ('page-saved-chooseballotpaper','page-saved-chooseballotpaper',from_base64('cGFnZS1zYXZlZC1jaG9vc2ViYWxsb3RwYXBlcg=='),from_base64( 'ZGl2LmNvbnRhaW5lci1mbHVpZAoJZGl2LmNvbnRhaW5lcgoJCWRpdi5yb3cKCQkJZGl2LmNvbCAh
e2Ntcy5tZCgnY2hvb3NlX2JhbGxvdHBhcGVyX3NhdmVkJyl9CgkJZGl2LnJvdwoJCQlkaXYuY29s
ICF7Y21zLm1kKCdjaG9vc2VfYmFsbG90cGFwZXJfc2F2ZWQyJyl9Cg==') );

thomashoffmann@MacBook-Pro-von-Thomas tualo % ./ds/src/sqlexport/export_pug_template 
ERROR 1046 (3D000) at line 1: No database selected

thomashoffmann@MacBook-Pro-von-Thomas tualo % code ./ds/src/sqlexport/export_pug_template
thomashoffmann@MacBook-Pro-von-Thomas tualo % ./ds/src/sqlexport/export_pug_template page owkiel
insert ignore into ds_pug_templates (name,id,note,template) values ('page','page',from_base64('cGFnZQ=='),from_base64( 'ZXh0ZW5kcyBwYWdlLW1haW4KaW5jbHVkZSBwYWdlLW1peGluLWNoZWNrYm94CmluY2x1ZGUgcGFn
ZS1taXhpbi1iYWxsb3RwYXBlci1tYXgKaW5jbHVkZSBwYWdlLXR1YWxvY21zLWJpbGRlcgoKYmxv
Y2sgY29udGVudAoJY2FzZSBjbXMud21zLmdldE5leHRTdGF0ZSgpCiAgICAJd2hlbiAnVHVhbG9c
T2ZmaWNlXE9ubGluZVZvdGVcU3RhdGVzXExvZ2luJwogICAgICAgIAlpbmNsdWRlIHBhZ2UtbG9n
aW4KICAgIAl3aGVuICdUdWFsb1xPZmZpY2VcT25saW5lVm90ZVxTdGF0ZXNcTGVnaXRpbWF0aW9u
JwogICAgICAgIAlpbmNsdWRlIHBhZ2UtbGVnaXRpbWF0aW9uCiAgICAgICAgd2hlbiAnVHVhbG9c
T2ZmaWNlXE9ubGluZVZvdGVcU3RhdGVzXExvZ291dCcKICAgICAgICAJaW5jbHVkZSBwYWdlLWxv
Z291dAogICAgICAgIHdoZW4gJ1R1YWxvXE9mZmljZVxPbmxpbmVWb3RlXFN0YXRlc1xDaG9vc2VC
YWxsb3RwYXBlcicKICAgICAgICAJaW5jbHVkZSBwYWdlLWNob29zZWJhbGxvdHBhcGVyCiAgICAg
ICAgd2hlbiAnVHVhbG9cT2ZmaWNlXE9ubGluZVZvdGVcU3RhdGVzXEJhbGxvdHBhcGVyJwogICAg
ICAgIAlpbmNsdWRlIHBhZ2UtYmFsbG90cGFwZXIKICAgICAgICB3aGVuICdUdWFsb1xPZmZpY2Vc
T25saW5lVm90ZVxTdGF0ZXNcQmFsbG90cGFwZXJPdmVydmlldycKICAgICAgICAJaW5jbHVkZSBw
YWdlLW92ZXJ2aWV3CiAgICAgICAgd2hlbiAnVHVhbG9cT2ZmaWNlXE9ubGluZVZvdGVcU3RhdGVz
XFNhdmVDb21wbGV0ZWRDaG9vc2VCYWxsb3RwYXBlcicKICAgICAgICAJaW5jbHVkZSBwYWdlLXNh
dmVkLWNob29zZWJhbGxvdHBhcGVyCiAgICAgICAgICAgIGluY2x1ZGUgcGFnZS1jaG9vc2ViYWxs
b3RwYXBlcgogICAgICAgIHdoZW4gJ1R1YWxvXE9mZmljZVxPbmxpbmVWb3RlXFN0YXRlc1xMb2dp
bkFsbHJlYWR5Vm90ZWRFcnJvcicKICAgICAgICAJLXZhciBtc2cgPSAiRsO8ciBkaWVzZW4gU3Rp
bW16ZXR0ZWwgd3VyZGUgYmVyZWl0cyBnZXfDpGhsdC4iCiAgICAgICAgICAgIGluY2x1ZGUgcGFn
ZS1lcnJvcgogICAgICAgIHdoZW4gJ1R1YWxvXE9mZmljZVxPbmxpbmVWb3RlXFN0YXRlc1xTYXZl
Q29tcGxldGVkJwogICAgICAgIAlpbmNsdWRlIHBhZ2Utc2F2ZWQKICAgICAgICB3aGVuICdUdWFs
b1xPZmZpY2VcT25saW5lVm90ZVxTdGF0ZXNcRXJyb3InCiAgICAgICAgCWluY2x1ZGUgcGFnZS1l
cnJvcgogICAgICAgIHdoZW4gJ1R1YWxvXE9mZmljZVxPbmxpbmVWb3RlXFN0YXRlc1xCYWxsb3RQ
YXBlckFsbHJlYWR5Vm90ZWRFcnJvcicKICAgICAgICAJLXZhciBtc2cgPSAiRsO8ciBkaWVzZW4g
U3RpbW16ZXR0ZWwgd3VyZGUgYmVyZWl0cyBnZXfDpGhsdC4iCiAgICAgICAgICAgIGluY2x1ZGUg
cGFnZS1lcnJvcgogICAgICAgIHdoZW4gJ1R1YWxvXE9mZmljZVxPbmxpbmVWb3RlXFN0YXRlc1xT
ZXNzaW9uSW52YWxpZEVycm9yJwogICAgICAgIAktdmFyIG1zZyA9ICJJaHJlIFNpdHp1bmcgaXN0
IGFiZ2VsYXVmZW4uIgogICAgICAgICAgICBpbmNsdWRlIHBhZ2UtZXJyb3IKICAgICAgICB3aGVu
ICdUdWFsb1xPZmZpY2VcT25saW5lVm90ZVxTdGF0ZXNcU2Vzc2lvbkJhbGxvdHBhcGVyU2F2ZUVy
cm9yJwogICAgICAgIAktdmFyIG1zZyA9ICJFcyBnaWJ0IGJlcmVpdHMgZWluZSB3ZWl0ZXJlIEFu
bWVsZHVuZy4iCiAgICAgICAgICAgIGluY2x1ZGUgcGFnZS1lcnJvcgogICAgICAgIGRlZmF1bHQK
ICAgICAgICAJaW5jbHVkZSBwYWdlLW1haW50ZW5hbmNlCiAgICAgICAgICAgICAgICAKICAgICAg
ICAgICAgICAg') );
 insert ignore into ds_pug_templates (name,id,note,template) values ('page-ballotpaper','page-ballotpaper',from_base64('cGFnZS1iYWxsb3RwYXBlcg=='),from_base64( 'LSB2YXIgZGlzYWJsZWQ9dHJ1ZQotIHZhciBiYWNrZ3JvdW5kX2NvbG9yPSJ2YXIoLS1icy1saWdo
dC10ZXh0KSIKaWYgY21zLndtcy5nZXROZXh0U3RhdGUoKT09J1R1YWxvXE9mZmljZVxPbmxpbmVW
b3RlXFN0YXRlc1xCYWxsb3RwYXBlcicKICAgIC0gZGlzYWJsZWQ9ZmFsc2UKICAgIC0gYmFja2dy
b3VuZF9jb2xvcj1jbXMuYmFsbG90cGFwZXIuZmFyYmUKCmZvcm0ucGFnZS1iYWxsb3RwYXBlci5j
b250YWluZXItZmx1aWQobWV0aG9kPSJwb3N0IikKCWRpdi5jb250YWluZXIKICAgIAlpbmNsdWRl
IHBhZ2UtYmFsbG90cGFwZXItdGl0bGUKCQlkaXYucm93CgkJCWluY2x1ZGUgcGFnZS1iYWxsb3Rw
YXBlci10YWJsZQogICAgICAgIGluY2x1ZGUgcGFnZS1iYWxsb3RwYXBlci1mb290ZXIKCQlpbmNs
dWRlIHBhZ2UtYmFsbG90cGFwZXItYnV0dG9ucwoK') );
 insert ignore into ds_pug_templates (name,id,note,template) values ('page-ballotpaper-buttons','page-ballotpaper-buttons',from_base64('cGFnZS1iYWxsb3RwYXBlci1idXR0b25z'),from_base64( 'ZGl2LnJvdy5idXR0b25zCglkaXYuY29sCgkgICAgaW5wdXQodHlwZT0iaGlkZGVuIixuYW1lPSJz
ZW5kIix2YWx1ZT0iMSIpCiAgICAJYnV0dG9uLmJ0bi5idG4tc3VjY2Vzcyh0eXBlPSJzdWJtaXQi
KSAhe2Ntcy50eHQoJ2JhbGxvdHBhcGVyX3N1Ym1pdF9idXR0b24nKX0K') );
 insert ignore into ds_pug_templates (name,id,note,template) values ('page-ballotpaper-footer','page-ballotpaper-footer',from_base64('cGFnZS1iYWxsb3RwYXBlci1mb290ZXI='),from_base64( 'ZGl2LnJvdwoJLSB2YXIgdGV4dCA9IGNtcy5tYXJrZG93bihjbXMudHh0KCdzdWJtaXRfZmlyc3Qn
KSkKCWRpdi5jb2wgIXt0ZXh0fQ==') );
 insert ignore into ds_pug_templates (name,id,note,template) values ('page-ballotpaper-table','page-ballotpaper-table',from_base64('cGFnZS1iYWxsb3RwYXBlci10YWJsZQ=='),from_base64( 'dGFibGUudGFibGUudGFibGUtc3RyaXBlZAoJdGhlYWQKCQl0cgoJCQl0aChzY29wZT0iY29sIikg
Jm5ic3A7CgkJCXRoLmNoZWNrLmFsaWduLW1pZGRsZShzY29wZT0iY29sIixzdHlsZT0iYmFja2dy
b3VuZC1jb2xvcjoiK2JhY2tncm91bmRfY29sb3IpCiAgICAgICAgICAgIAkrYmFsbG90cGFwZXJt
YXgoY21zLmJhbGxvdHBhcGVyKQoJdGJvZHkKCQllYWNoIGJhbGxvdHBhcGVyX2dyb3VwIGluIGNt
cy5iYWxsb3RwYXBlcl9ncm91cHMKCQkJZWFjaCBjYW5kaWRhdGUgaW4gYmFsbG90cGFwZXJfZ3Jv
dXAuY2FuZGlkYXRlcwoJCQkJdHIKCQkJCQl0ZChzY29wZT0icm93IikKICAgICAgICAgICAgICAg
ICAgICAJaW5jbHVkZSBwYWdlLWJhbGxvdHBhcGVyLXRhYmxlLWNvbnRlbnQKCQkJCQl0ZC5hbGln
bi1taWRkbGUoc2NvcGU9InJvdyIsc3R5bGU9ImJhY2tncm91bmQtY29sb3I6IitiYWNrZ3JvdW5k
X2NvbG9yKQogICAgICAgICAgICAgICAgICAgICAgICArY2hlY2tib3goCiAgICAgICAgICAgICAg
ICAgICAgICAgIAknQicrY21zLndtcy52b3RlcigpLmJhbGxvdHBhcGVyKCkuZ2V0TWFwSGFzaChj
YW5kaWRhdGUuaWQpLAogICAgICAgICAgICAgICAgICAgICAgICAgICAgJ2NhbmRpZGF0ZVtdJywK
ICAgICAgICAgICAgICAgICAgICAgICAgICAgIGNtcy53bXMudm90ZXIoKS5iYWxsb3RwYXBlcigp
LmdldE1hcEhhc2goY2FuZGlkYXRlLmlkKSwKICAgICAgICAgICAgICAgICAgICAgICAgICAgIGNt
cy53bXMudm90ZXIoKS5iYWxsb3RwYXBlcigpLmlzQ2hlY2tlZChjYW5kaWRhdGUuaWQpLAogICAg
ICAgICAgICAgICAgICAgICAgICAgICAgZGlzYWJsZWQKICAgICAgICAgICAgICAgICAgICAgICAg
KQo=') );
 insert ignore into ds_pug_templates (name,id,note,template) values ('page-ballotpaper-table-content','page-ballotpaper-table-content',from_base64('cGFnZS1iYWxsb3RwYXBlci10YWJsZS1jb250ZW50'),from_base64( 'ZWFjaCByb3cgaW4gY21zLnJvd3MKCWRpdihjbGFzcz0icm93Iityb3cucHJlZml4KyIgIityb3cu
cm93X25hbWUpCgkJZWFjaCBjb2wgaW4ganNvbl9kZWNvZGUocm93LmNvbHVtbnMsdHJ1ZSkKCQkJ
ZGl2KGNsYXNzPSJjb2wiK2NvbC5wcmVmaXgrIiAiK2NvbC5jb2x1bW5fbmFtZSkKCQkJCWVhY2gg
ZmllbGQgaW4gY29sLmRlZmluaXRpb24KCQkJCQlpZiBmaWVsZC5odG1sdGFnPT0naW1nJwoJCQkJ
CQlpbWcoCgkJCQkJCQljbGFzcz1maWVsZC5jb2x1bW5fZmllbGQKCQkJCQkJCXN0eWxlPSJib3Jk
ZXItcmFkaXVzOiAxMHB4OyIKCQkJCQkJCXNyYz0iL2ltYWdlcy9wb3J0cmFpdC8iK2NhbmRpZGF0
ZVtmaWVsZC5jb2x1bW5fZmllbGRdKyIucG5nIgoJCQkJCQkpCgkJCQkJZWxzZQoJCQkJCQlwKGNs
YXNzPWZpZWxkLmNvbHVtbl9maWVsZCkgIXtjYW5kaWRhdGVbZmllbGQuY29sdW1uX2ZpZWxkXX0=') );
 insert ignore into ds_pug_templates (name,id,note,template) values ('page-ballotpaper-title','page-ballotpaper-title',from_base64('cGFnZS1iYWxsb3RwYXBlci10aXRsZQ=='),from_base64( 'ZGl2LnJvdwoJZGl2LmNvbAogICAgCS8vIC50ZXh0LWNvbnRvdXIKICAgIAloNChzdHlsZT0iY29s
b3I6IitiYWNrZ3JvdW5kX2NvbG9yKSAhe2Ntcy5iYWxsb3RwYXBlci5uYW1lfQoJCQ==') );
 insert ignore into ds_pug_templates (name,id,note,template) values ('page-chooseballotpaper','page-chooseballotpaper',from_base64('cGFnZS1jaG9vc2ViYWxsb3RwYXBlcg=='),from_base64( 'LXZhciBhdmFpbGFibGVCYWxsb3RwYXBlcnMgPSBjbXMud21zLnZvdGVyKCkuYXZhaWxhYmxlQmFs
bG90cGFwZXJzKCkKLXZhciBncm91cHMgPSBjbXMud21zLnZvdGVyKCkuYXZhaWxhYmxlQmFsbG90
cGFwZXJHcm91cHMoKQotdmFyIGxhc3RJbmRleD0tMQpkaXYucGFnZS1jaG9vc2ViYWxsb3RwYXBl
ci5jb250YWluZXItZmx1aWQKCWRpdi5jb250YWluZXIKCQlkaXYucm93CgkJCWRpdi5jb2wgQml0
dGUgd8OkaGxlbiBTaWUgZWluZW4gU3RpbW16ZXR0ZWwgYXVzLCBmw7xyIHdlbGNoZW4gU2llIGpl
dHp0IGFic3RpbW1lbiBtw7ZjaHRlbi4KZGl2LnBhZ2UtY2hvb3NlYmFsbG90cGFwZXIuY29udGFp
bmVyLWZsdWlkCglkaXYuY29udGFpbmVyCgkJZWFjaCBncm91cCBpbiBncm91cHMKCQkJZGl2LnBh
Z2UtY2hvb3NlYmFsbG90cGFwZXIucm93CgkJCQlkaXYuY29sLWF1dG8KCQkJCQkvLyAudGV4dC1j
b250b3VyCgkJCQkJaDQoc3R5bGU9ImNvbG9yOiIrZ3JvdXAuY29sb3IrIjsiKSAhe2dyb3VwLm5h
bWV9CgkJCQlkaXYuY29sLnRleHQtZW5kCgkJCQkJc3BhbiAoIXtncm91cC5jb3VudH0pCgkJCQkJ
CgkJCWVhY2ggYnAsaW5kZXggaW4gYXZhaWxhYmxlQmFsbG90cGFwZXJzCgkJCQktIHZhciBkYXRh
ID0gYnAuZ2V0Vm90ZXJEYXRhKCk7CgkJCQlpZiBncm91cC5pZCA9PSBicC5nZXRCYWxsb3RwYXBl
cklkKCkKCQkJCQktIGxhc3RJbmRleD1pbmRleDsKCQkJCQlkaXYucm93CgkJCQkJCWRpdi5jb2wt
MQoJCQkJCQlkaXYuY29sCgkJCQkJCQlhKGhyZWY9Ij9iYWxsb3RwYXBlckluZGV4PSIraW5kZXgp
ICF7ZGF0YS5wb3N0X25hbWUyfQoJCQkJCQlkaXYuY29sLTEKCQkJaWYgZ3JvdXAuY291bnQ+MSAg
ICAgICAgICAgICAgICAgICAgICAgIAoJCQkJZGl2LnJvdwoJCQkJCWRpdi5jb2wtMSAmbmJzcDsK
CQkJCQlkaXYuY29sLWF1dG8KCQkJCQkJc3BhbiBVbSBmw7xyIGFsbGUgVW50ZXJuZWhtZW4gbWl0
IGRlbSBTdGltbXpldHRlbCAiIXtncm91cC5uYW1lfSIgaWRlbnRpc2NoIGFienVzdGltbWVuLCBr
bGlja2VuIFNpZSBiaXR0ZSAKCQkJCQkJYShocmVmPSI/Z3JvdXBlZD0xJmJhbGxvdHBhcGVySW5k
ZXg9IitsYXN0SW5kZXgpIGhpZXIgICAgICAgICAgICAKCQkJCQkJc3BhbiAuCgkvLyBkaXYuY29u
dGFpbmVyCgkJZWFjaCBicCBpbiBhdmFpbGFibGVCYWxsb3RwYXBlcnMKCQkJLSB2YXIgZGF0YSA9
IGJwLmdldFZvdGVyRGF0YSgpOwoJCQlkaXYucm93CgkJCQlkaXYuY29sIAoJCQkJCWEoaHJlZj0i
P2JhbGxvdHBhcGVySW5kZXg9IitpbmRleCkKCQkJCQkJaDQgIXticC5nZXRCYWxsb3RwYXBlck5h
bWUoKX0KCQkJCQkJcCAhe2RhdGEucG9zdF9uYW1lMn0KCQkJCQktIGluZGV4ID0gaW5kZXggKzEK
Cg==') );
 insert ignore into ds_pug_templates (name,id,note,template) values ('page-debug','page-debug',from_base64('cGFnZS1kZWJ1Zw=='),from_base64( 'ZGl2LnBhZ2UtZGVidWcuY29udGFpbmVyLWZsdWlkLmFsZXJ0LmFsZXJ0LWRhbmdlcihyb2xlPSJh
bGVydCIpCglkaXYuY29udGFpbmVyCgkJZGl2LnJvdwoJCQlkaXYuY29sLnRleHQtdHJ1bmNhdGUg
TmV4dFN0YXRlICF7Y21zLndtcy5nZXROZXh0U3RhdGUoKX0KCQlkaXYucm93CgkJCWRpdi5jb2wu
dGV4dC10cnVuY2F0ZSBDdXJyZW50U3RhdGUgIXtjbXMud21zLmdldEN1cnJlbnRTdGF0ZSgpfQog
ICAgICAgIGRpdi5yb3cKICAgICAgICAJZGl2LmNvbC50ZXh0LXRydW5jYXRlIFByZXZTdGF0ZSAh
e2Ntcy53bXMuZ2V0UHJldlN0YXRlKCl9Cg==') );
 insert ignore into ds_pug_templates (name,id,note,template) values ('page-documentation','page-documentation',from_base64('cGFnZS1kb2N1bWVudGF0aW9u'),from_base64( 'ZXh0ZW5kcyBwYWdlLW1haW4KaW5jbHVkZSBwYWdlLW1peGluLWNoZWNrYm94CmluY2x1ZGUgcGFn
ZS1taXhpbi1iYWxsb3RwYXBlci1tYXgKCmJsb2NrIGNvbnRlbnQKICAgIGRpdi5jb250YWluZXIt
Zmx1aWQKCSAgICBkaXYuY29udGFpbmVyCiAgICAJICAgIGRpdi5yb3cKICAgICAgICAJICAgIGRp
di5jb2wgIXtjbXMubWFya2Rvd24oY21zLnR4dCgnZG9jdW1lbnRhdGlvbl9ibG9ja18wJykpfQog
ICAgCSAgICBkaXYucm93CiAgICAgICAgCSAgICBkaXYuY29sICF7Y21zLm1hcmtkb3duKGNtcy50
eHQoJ2RvY3VtZW50YXRpb25fYmxvY2tfMScpKX0KICAgIAkgICAgZGl2LnJvdwogICAgICAgIAkg
ICAgZGl2LmNvbCAhe2Ntcy5tYXJrZG93bihjbXMudHh0KCdkb2N1bWVudGF0aW9uX2Jsb2NrXzIn
KSl9CiAgICAJICAgIGRpdi5yb3cKICAgICAgICAJICAgIGRpdi5jb2wgIXtjbXMubWFya2Rvd24o
Y21zLnR4dCgnZG9jdW1lbnRhdGlvbl9ibG9ja18zJykpfQogICAgCSAgICBkaXYucm93CiAgICAg
ICAgCSAgICBkaXYuY29sICF7Y21zLm1hcmtkb3duKGNtcy50eHQoJ2RvY3VtZW50YXRpb25fYmxv
Y2tfNCcpKX0KICAgIAkgICAgZGl2LnJvdwogICAgICAgIAkgICAgZGl2LmNvbCAhe2Ntcy5tYXJr
ZG93bihjbXMudHh0KCdkb2N1bWVudGF0aW9uX2Jsb2NrXzUnKSl9CiAgICAJICAgIGRpdi5yb3cK
ICAgICAgICAJICAgIGRpdi5jb2wgIXtjbXMubWFya2Rvd24oY21zLnR4dCgnZG9jdW1lbnRhdGlv
bl9ibG9ja182JykpfQog') );
 insert ignore into ds_pug_templates (name,id,note,template) values ('page-error','page-error',from_base64('cGFnZS1lcnJvcg=='),from_base64( 'ZGl2LnBhZ2UtZXJyb3IuY29udGFpbmVyLWZsdWlkCglkaXYuY29udGFpbmVyCgkJZGl2LnJvdwoJ
CQlkaXYuY29sIEVzIGlzdCBlaW4gRmVobGVyIHBhc3NpZXJ0IAoJCWRpdi5yb3cKCQkJZGl2LmNv
bCAhe21zZ30K') );
 insert ignore into ds_pug_templates (name,id,note,template) values ('page-footer','page-footer',from_base64('cGFnZS1mb290ZXI='),from_base64( 'Zm9vdGVyLnBhZ2UtZm9vdGVyLmNvbnRhaW5lci1mbHVpZAoJZGl2LmNvbnRhaW5lcgoJCWRpdi5y
b3cKICAgICAgICAgICAgZGl2LmNvbC1tZC00CiAgICAgICAgICAgIAl1bC5taWQtbGlua2xpc3Qo
c3R5bGU9Imxpc3Qtc3R5bGUtdHlwZTogbm9uZTsgbWFyZ2luOiAwOyAgcGFkZGluZzogMDsiKQoJ
ICAgICAgICAgICAgCWVhY2ggcmVjb3JkIGluIGNtcy5saW5rcwogICAgICAgICAgICAgICAgICAg
IAlpZiByZWNvcmQuZm9vdGVyMT09MQoJICAgIAkgICAgICAgICAgICAJbGkuZm9vdGVyLW5hdi1p
dGVtCiAgICAJICAgICAgICAgICAgICAgICAgICAJYShocmVmPXJlY29yZC51cmwsdGFyZ2V0PXJl
Y29yZC52YXJ0YXJnZXQscmVsPSJub29wZW5lciIpPXJlY29yZC50aXRsZQogICAgICAgICAgICBk
aXYuY29sLW1kLTQKICAgICAgICAgICAgCXVsLm1pZC1saW5rbGlzdChzdHlsZT0ibGlzdC1zdHls
ZS10eXBlOiBub25lOyBtYXJnaW46IDA7ICBwYWRkaW5nOiAwOyIpCgkgICAgICAgICAgICAJZWFj
aCByZWNvcmQgaW4gY21zLmxpbmtzCiAgICAgICAgICAgICAgICAgICAgCWlmIHJlY29yZC5mb290
ZXIyPT0xCgkgICAgCSAgICAgICAgICAgIAlsaS5mb290ZXItbmF2LWl0ZW0KICAgIAkgICAgICAg
ICAgICAgICAgICAgIAlhKGhyZWY9cmVjb3JkLnVybCx0YXJnZXQ9cmVjb3JkLnZhcnRhcmdldCxy
ZWw9Im5vb3BlbmVyIik9cmVjb3JkLnRpdGxlCiAgICAgICAgICAgIAogICAgICAgIAlkaXYuY29s
LW1kLTQKICAgICAgICAgICAgCXVsLm1pZC1saW5rbGlzdChzdHlsZT0ibGlzdC1zdHlsZS10eXBl
OiBub25lOyBtYXJnaW46IDA7ICBwYWRkaW5nOiAwOyIpCgkgICAgICAgICAgICAJZWFjaCByZWNv
cmQgaW4gY21zLmxpbmtzCiAgICAgICAgICAgICAgICAgICAgCWlmIHJlY29yZC5mb290ZXIzPT0x
CgkgICAgCSAgICAgICAgICAgIAlsaS5mb290ZXItbmF2LWl0ZW0KICAgIAkgICAgICAgICAgICAg
ICAgICAgIAlhKGhyZWY9cmVjb3JkLnVybCx0YXJnZXQ9cmVjb3JkLnZhcnRhcmdldCxyZWw9Im5v
b3BlbmVyIik9cmVjb3JkLnRpdGxlCiAgICAJZGl2LnJvdwogICAgICAgIAlkaXYuY29sLnRleHQt
Y2VudGVyCiAgICAgICAgICAgICAgc3Bhbi5icC1mcy1zbWFsbCDCqSAhe2Ntcy50eHQoJ2NvcHly
aWdodCcpfSAK') );
 insert ignore into ds_pug_templates (name,id,note,template) values ('page-header','page-header',from_base64('cGFnZS1oZWFkZXI='),from_base64( 'aGVhZGVyLnBhZ2UtaGVhZGVyLmNvbnRhaW5lci1mbHVpZAogICAgZGl2LmNvbnRhaW5lcgogICAg
ICAgIGRpdi5yb3cKICAgICAgICAgICAgZGl2LmNvbC1tZC00LnRleHQtc3RhcnQKICAgICAgICAg
ICAgICAgIGEoaHJlZj1jbXMudHh0KCdpaGtfbG9nb19saW5rJyksdGFyZ2V0PSJfYmxhbmsiLHJl
bD0ibm9vcGVuZXIiKQogICAgICAgICAgICAgICAgICAgICt0dWFsb2Ntc2JpbGQoJ3RpdGVsJywn
V2FobGxvZ28nLCdoZWlnaHQ6IDIuMGNtJykKICAgICAgICAgICAgICAgICAgICAvLyBpbWcoc3Jj
PSIvaW1hZ2VzL0xvZ29fSUhLLUtpZWwuc3ZnIiwgc3R5bGU9ImhlaWdodDogMi4wY20iKQogICAg
ICAgICAgICBkaXYuY29sLW1kLTQudGV4dC1jZW50ZXIKICAgICAgICAgICAgICAgIGEuZC1ub25l
LmQtbWQtaW5saW5lKGhyZWY9Y21zLnR4dCgnd2FobF9sb2dvX2xpbmsnKSx0YXJnZXQ9Il9ibGFu
ayIscmVsPSJub29wZW5lciIpCiAgICAgICAgICAgICAgICAJK3R1YWxvY21zYmlsZCgndGl0ZWwn
LCdXYWhsbG9nbycsJycpCiAgICAgICAgICAgIGRpdi5jb2wtbWQtNC50ZXh0LWVuZAogICAgICAg
ICAgICAgICAgZGl2LnJvdwogICAgICAgICAgICAgICAgICAgIGRpdi5jb2wKICAgICAgICAgICAg
ICAgICAgICAgICAgYShocmVmPSJ0ZWw6IitjbXMudHh0KCdoZWFkZXJfdGVsZWZvbl9saW5rJykp
CiAgICAgICAgICAgICAgICAgICAgICAgICAgICBpLmZhci5mYS1waG9uZS1hbHQKICAgICAgICAg
ICAgICAgICAgICAgICAgICAgICAgICBzcGFuLmQtbm9uZS5kLXNtLWlubGluZSAmbmJzcDsmbmJz
cDshe2Ntcy50eHQoJ2hlYWRlcl90ZWxlZm9uX3RleHQnKX0gCiAgICAgICAgICAgICAgICAtaWYg
KGNtcy53bXMudm90ZXIoKS5pc0xvZ2dlZEluKCkgPT0gdHJ1ZSApCiAgICAgICAgICAgICAgICAg
ICAgZGl2LnJvdwogICAgICAgICAgICAgICAgICAgICAgICBkaXYuY29sCiAgICAgICAgICAgICAg
ICAgICAgICAgICAgICBhLmJ0bi5idG4tcHJpbWFyeShocmVmPSIuLz9sb2dvdXQ9MSIscmVsPSJu
b29wZW5lciIgKSAhe2Ntcy5tZCgnYnV0dG9uX2xvZ291dCcpfQogICAgZGl2LnBhZ2UtY2xhaW0u
Y29udGFpbmVyLWZsdWlkLmJnLXByaW1hcnkKICAgICAgICBkaXYuY29sLnBhZ2UtY2xhaW0KICAg
ICAgICAgICAgc3BhbiAhe2Ntcy50eHQoJ2xvZ2luZm9ybV9saWdodF9saW5lJyl9IAogICAgICAg
ICAgICBpZiBjbXMudHh0KCdsb2dpbmZvcm1fZGFya19saW5lJykubGVuZ3RoID4gMQogICAgICAg
ICAgICAgICAgYnIKICAgICAgICAgICAgICAgIHNwYW4oc3R5bGU9ImZvbnQtd2VpZ2h0OiBMaWdo
dGVzdDsiKSAhe2Ntcy50eHQoJ2xvZ2luZm9ybV9kYXJrX2xpbmUnKX0g') );
 insert ignore into ds_pug_templates (name,id,note,template) values ('page-legitimation','page-legitimation',from_base64('cGFnZS1sZWdpdGltYXRpb24='),from_base64( 'ZGl2LnBhZ2UtbGVnaXRpbWF0aW9uLmNvbnRhaW5lci1mbHVpZAoJZGl2LmNvbnRhaW5lcgoJCWRp
di5yb3cKCQkJZGl2LmNvbCAhe2Ntcy5tYXJrZG93bihjbXMudHh0KCdsZWdpdGltYXRpb24nKSl9
CmRpdi5jb250YWluZXItZmx1aWQKICAgIGRpdi5jb250YWluZXIKICAgIAlkaXYucm93CiAgICAg
ICAgCWZvcm0uY29sKG1ldGhvZD0icG9zdCIsYWN0aW9uPSIuLyIpCiAgICAgICAgICAgIAlpbnB1
dCgKICAgICAgICAgIAkJCXR5cGU9ImhpZGRlbiIsCgkJCSAgICAgICAgbmFtZT0ibG9nb3V0IiwK
CQkJICAgICAgICB2YWx1ZT0xCgkJCSAgICApCiAgICAgICAgICAgICAgICBidXR0b24uYnRuLmJ0
bi13YXJuaW5nICF7Y21zLm1hcmtkb3duKGNtcy50eHQoJ2xlZ2l0aW1hdGlvbl9ubycpKX0KICAg
ICAgICAJZm9ybS5jb2wobWV0aG9kPSJwb3N0IixhY3Rpb249Ii4vIikKICAgICAgICAgICAgCWlu
cHV0KAogICAgICAgICAgCQkJdHlwZT0iaGlkZGVuIiwKCQkJICAgICAgICBuYW1lPSJsZWdpdGlt
YXRpb24iLAoJCQkgICAgICAgIHZhbHVlPWNtcy5sZWdpdGltYXRpb25fdXVpZAoJCQkgICAgKQog
ICAgICAgICAgICAgICAgaW5wdXQoCiAgICAgICAgICAJCQl0eXBlPSJoaWRkZW4iLAoJCQkgICAg
ICAgIG5hbWU9ImxlZ2l0aW1hdGlvbl9jb25maXJtZWQiLAoJCQkgICAgICAgIHZhbHVlPTEKCQkJ
ICAgICkKICAgICAgICAgICAgICAgIGJ1dHRvbi5idG4uYnRuLXN1Y2Nlc3MgIXtjbXMubWFya2Rv
d24oY21zLnR4dCgnbGVnaXRpbWF0aW9uX3llcycpKX0KaW5jbHVkZSBwYWdlLWxlZ2l0aW1hdGlv
bi1zdWJ0ZXh0Cg==') );
 insert ignore into ds_pug_templates (name,id,note,template) values ('page-legitimation-subtext','page-legitimation-subtext',from_base64('cGFnZS1sZWdpdGltYXRpb24tc3VidGV4dA=='),from_base64( 'ZGl2LmNvbnRhaW5lci1mbHVpZC5wYWdlLWxlZ2l0aW1hdGlvbi1zdWJ0ZXh0CglkaXYuY29udGFp
bmVyCgkJZGl2LnJvdwogICAgICAgIAlkaXYuY29sLmxlZ2l0aW1hdGlvbiAhe2Ntcy5tYXJrZG93
bihjbXMudHh0KCdsZWdpdGltYXRpb25fc3VidGV4dCcpKX0K') );
 insert ignore into ds_pug_templates (name,id,note,template) values ('page-login','page-login',from_base64('cGFnZS1sb2dpbg=='),from_base64( 'Zm9ybS5wYWdlLWxvZ2luLmNvbnRhaW5lci1mbHVpZChtZXRob2Q9InBvc3QiLGFjdGlvbj0iLi8i
KQoJZGl2LmNvbnRhaW5lcgoJCWRpdi5yb3cuYWxlcnQuYWxlcnQtcHJpbWFyeQogICAgCQlkaXYu
Y29sICF7Y21zLm1hcmtkb3duKGNtcy50eHQoJ2xvZ2luZm9ybV93ZWxsY29tZV90ZXh0JykpfQoJ
CWRpdi5yb3cKICAgIAkJZGl2LmNvbCAhe2Ntcy5tYXJrZG93bihjbXMudHh0KCdsb2dpbmZvcm1f
c2VjdXJpdHknKSl9IAoJCWRpdi5yb3cKICAgIAkJZGl2LmNvbAogICAgICAgIAkJaW5jbHVkZSBw
YWdlLWxvZ2luLWZvcm0K') );
 insert ignore into ds_pug_templates (name,id,note,template) values ('page-login-form','page-login-form',from_base64('cGFnZS1sb2dpbi1mb3Jt'),from_base64( 'LXZhciBwYXR0ZXJuPSJbQUJDREVGR0hKS0xNTlBSU1RVVlhZWmFiY2RlZmdoaWprbXBzdHV2eHl6
MDEyMzQ1Njc4OV17OH0iCmlucHV0LmhpbnQtY2lyY2xlLWNoZWNrYm94KAogIGlkPSdsb2dpbnRy
aWdnZXInCiAgbmFtZT0nYWNjZXB0JwogIHR5cGU9ImNoZWNrYm94IgogIGNoZWNrZWQ9ZmFsc2UK
ICBkaXNhYmxlZD1mYWxzZQogIHJlcXVpcmVkPXRydWUKKQpsYWJlbC5jb250YWluZXIoIGZvcj0n
bG9naW50cmlnZ2VyJyApCglkaXYucm93CgkJZGl2LmNvbC1hdXRvCiAgICAJCWkuZmFyLmZhLXRp
bWVzCgkJZGl2LmNvbCAhe2Ntcy5tYXJrZG93bihjbXMudHh0KCdsb2dpbmZvcm1fYm94aGlud2Vp
cycpKX0KICAgIAkKZGl2LmZvcm1ib3gKICAgIGRpdi5mb3JtLWdyb3VwCiAgICAgICAgbGFiZWwo
Zm9yPSJwMSIpIExvZ2luCiAgICAgICAgaW5wdXQuZm9ybS1jb250cm9sLmNvbCgKICAgICAgICAJ
dHlwZT0idGV4dCIsCiAgICAgICAgICAgIHBhdHRlcm49cGF0dGVybiwKICAgICAgICAgICAgcGxh
Y2Vob2xkZXI9IkxvZ2luIiwKICAgICAgICAgICAgbWF4bGVuZ3RoPSI4IiwKICAgICAgICAgICAg
bmFtZT1jbXMud21zLnVzZXJuYW1lZmllbGQoKSwKICAgICAgICAgICAgaWQ9InAxIiwKICAgICAg
ICAgICAgcmVxdWlyZWQ9InRydWUiLAogICAgICAgICAgICB0aXRsZT1jbXMudHh0KCdmb3JtX2lu
cHV0X3RpdGxlJyksCiAgICAgICAgICAgIHZhbHVlPWNtcy5wMQogICAgICAgICkKICAgIGRpdi5m
b3JtLWdyb3VwKHN0eWxlPSJtYXJnaW4tYm90dG9tOiAxMHB4OyIpCiAgICAgICAgbGFiZWwoZm9y
PSJwMiIpIFBhc3N3b3J0CiAgICAgICAgaW5wdXQuZm9ybS1jb250cm9sLmNvbCgKICAgICAgICAJ
dHlwZT0icGFzc3dvcmQiLAogICAgICAgICAgICBwYXR0ZXJuPXBhdHRlcm4sCiAgICAgICAgICAg
IHBsYWNlaG9sZGVyPSJQYXNzd29ydCIsCiAgICAgICAgICAgIG1heGxlbmd0aD0iOCIsCiAgICAg
ICAgICAgIG5hbWU9Y21zLndtcy5wYXNzd29yZGZpZWxkKCksCiAgICAgICAgICAgIGlkPSJwMiIs
CiAgICAgICAgICAgIHJlcXVpcmVkPSJ0cnVlIiwKICAgICAgICAgICAgdGl0bGU9Y21zLnR4dCgn
Zm9ybV9pbnB1dF90aXRsZScpLAogICAgICAgICAgICB2YWx1ZT1jbXMucDIKICAgICAgICApCgog
ICAgYnIKICAgIGRpdiNjb29raWVEaXYucm93KHN0eWxlPSJkaXNwbGF5Om5vbmU7IikKICAgICAg
ICBkaXYuY29sICF7Y21zLm1hcmtkb3duKGNtcy50eHQoJ2Nvb2tpZV90ZXh0JykpfQogICAgCiAg
ICBkaXYucm93CiAgICAgICAgZGl2LmNvbAogICAgICAgICAgICBidXR0b24uYnRuLmJ0bi1zdWNj
ZXNzKHR5cGU9InN1Ym1pdCIpICF7Y21zLm1hcmtkb3duKGNtcy50eHQoJ2J1dHRvbl9sb2dpbicp
KX0=') );
 insert ignore into ds_pug_templates (name,id,note,template) values ('page-logout','page-logout',from_base64('cGFnZS1sb2dvdXQ='),from_base64( 'ZGl2LnBhZ2UtbG9nb3V0LmNvbnRhaW5lci1mbHVpZAoJZGl2LmNvbnRhaW5lcgoJCWRpdi5yb3cK
CQkJZGl2LmNvbCAhe2Ntcy5tZCgnYXNrbG9nb3V0X3RleHQnKX0KCQlkaXYucm93CgkJCWRpdi5j
b2wKICAgICAgICAgICAgCWEuYnRuLmJ0bi1pbmZvKAogICAgICAgICAgICAgICAgCWhyZWY9Ii4v
P2xvZ291dF9jb25maXJtZWQ9MSIsCiAgICAgICAgICAgICAgICAgICAgcmVsPSJub29wZW5lciIK
ICAgICAgICAgICAgICAgICkgIXtjbXMubWQoJ2Fza2xvZ291dF9idXR0b25fbG9nb3V0Jyl9CgkJ
CWRpdi5jb2wKICAgICAgICAgICAgCWEuYnRuLmJ0bi1pbmZvKAogICAgICAgICAgICAgICAgCWhy
ZWY9Ii4vP2xvZ291dF9jYW5jZWxlZD0xIiwKICAgICAgICAgICAgICAgICAgICByZWw9Im5vb3Bl
bmVyIgogICAgICAgICAgICAgICAgKSAhe2Ntcy5tZCgnYXNrbG9nb3V0X2J1dHRvbl9iYWNrJyl9
Cg==') );
 insert ignore into ds_pug_templates (name,id,note,template) values ('page-main','page-main',from_base64('cGFnZS1tYWlu'),from_base64( 'Lgpkb2N0eXBlIGh0bWwKaHRtbChsYW5nPSdkZScpCiAgICBoZWFkCiAgICAgICAgYmxvY2sgaGVh
ZAogICAgICAgICAgICBtZXRhKGNoYXJzZXQ9J3V0Zi04JykKCQkJbWV0YShuYW1lPSJmb3JtYXQt
ZGV0ZWN0aW9uIixjb250ZW50PSJ0ZWxlcGhvbmU9bm8iKQogICAgICAgICAgICBtZXRhKG5hbWU9
InZpZXdwb3J0Iixjb250ZW50PSJ3aWR0aD1kZXZpY2Utd2lkdGgsIGluaXRpYWwtc2NhbGU9MSwg
c2hyaW5rLXRvLWZpdD1ubyIpCiAgICAgICAgICAgIHRpdGxlICF7Y21zLnR4dCgnc2l0ZV90aXRs
ZScpfQoJCQlsaW5rKAogICAgICAgICAgICAJaHJlZj0iLi9ib290c3RyYXBidWlsZC9ib290c3Ry
YXAuY3NzIiAKICAgICAgICAgICAgICAgIHJlbD0ic3R5bGVzaGVldCIgCiAgICAgICAgICAgICAg
ICAKICAgICAgICAgICAgKQogICAgICAgICAgICBsaW5rKHJlbD0ic3R5bGVzaGVldCIsaHJlZj0i
L2ZvbnRhd2Vzb21lLXByby9jc3MvYWxsLmNzcyIpCiAgICAgICAgICAgIGxpbmsocmVsPSJzdHls
ZXNoZWV0IixocmVmPSIuL3BhZ2UuY3NzIikKICAgICAgICAgICAgc2NyaXB0KHR5cGU9InRleHQv
amF2YXNjcmlwdCIsc3JjPSIvanMvY29va2llLWNoZWNrLmpzIixkZWZlcikKCWJvZHkodGFiSW5k
ZXg9MCkKICAgIAlpbmNsdWRlIHBhZ2UtaGVhZGVyCiAgICAJYmxvY2sgY29udGVudAogICAgICAg
IGluY2x1ZGUgcGFnZS1kZWJ1ZwogICAgICAgIGluY2x1ZGUgcGFnZS1mb290ZXI=') );
 insert ignore into ds_pug_templates (name,id,note,template) values ('page-maintenance','page-maintenance',from_base64('cGFnZS1tYWludGVuYW5jZQ=='),from_base64( 'ZGl2LnBhZ2UtbWFpbnRlbmFuY2UuY29udGFpbmVyLWZsdWlkCglkaXYuY29udGFpbmVyCgkJZGl2
LnJvdwoJCQlkaXYuY29sICF7Y21zLm1kKCdtYWludGVuYW5jZScpfQo=') );
 insert ignore into ds_pug_templates (name,id,note,template) values ('page-mixin-ballotpaper-max','page-mixin-ballotpaper-max',from_base64('cGFnZS1taXhpbi1iYWxsb3RwYXBlci1tYXg='),from_base64( 'bWl4aW4gYmFsbG90cGFwZXJtYXgoYmFsbG90cGFwZXIpCgktIHZhciBrcmV1enRleHQ9J0tyZXV6
JwoJLSBpZiAoYmFsbG90cGFwZXIuc2l0emUgPiAxKQoJCS0ga3JldXp0ZXh0PSdLcmV1emUnCglk
aXYucm93LmFsaWduLW1pZGRsZS50ZXh0LWNlbnRlcgoJCXNwYW4gTWF4LgoJCWJyCgkJc3BhbiAh
e2JhbGxvdHBhcGVyLnNpdHplfQoJCWJyCgkJc3BhbiAhe2tyZXV6dGV4dH0K') );
 insert ignore into ds_pug_templates (name,id,note,template) values ('page-mixin-checkbox','page-mixin-checkbox',from_base64('cGFnZS1taXhpbi1jaGVja2JveA=='),from_base64( 'bWl4aW4gY2hlY2tib3goaWQsIG5hbWUsIHZhbHVlLCBjaGVja2VkLCBkaXNhYmxlZCwgcmVxdWly
ZWQsIGhpbnQpCiAgICBpbnB1dC5jaXJjbGUtY2hlY2tib3goCiAgICAgICAgaWQ9aWQKICAgICAg
ICBuYW1lPW5hbWUKICAgICAgICB2YWx1ZT12YWx1ZQogICAgICAgIHR5cGU9ImNoZWNrYm94Igog
ICAgICAgIGNoZWNrZWQ9Y2hlY2tlZAogICAgICAgIGRpc2FibGVkPWRpc2FibGVkCiAgICAgICAg
cmVxdWlyZWQ9cmVxdWlyZWQKICAgICkKICAgIGxhYmVsKCBmb3I9aWQgKQogICAgCWRpdgogICAg
ICAgIAlpLmZhci5mYS10aW1lcwogICAgICAgIHNwYW4gIXtoaW50fQo=') );
 insert ignore into ds_pug_templates (name,id,note,template) values ('page-overview','page-overview',from_base64('cGFnZS1vdmVydmlldw=='),from_base64( 'LSB2YXIga3JldXp0ZXh0PSdLcmV1eicKLSB2YXIgZGlzYWJsZWQ9dHJ1ZQotIHZhciBiYWNrZ3Jv
dW5kX2NvbG9yPSJ2YXIoLS1icy1saWdodC10ZXh0KSIKLSBpZiAoY21zLmJhbGxvdHBhcGVyLnNp
dHplID4gMSkKCS0ga3JldXp0ZXh0PSdLcmV1emUnCmZvcm0ucGFnZS1iYWxsb3RwYXBlci5jb250
YWluZXItZmx1aWQKCWRpdi5jb250YWluZXIKCQlpbmNsdWRlIHBhZ2UtYmFsbG90cGFwZXItdGl0
bGUKCQlkaXYucm93CgkJCWluY2x1ZGUgcGFnZS1iYWxsb3RwYXBlci10YWJsZQoJCWluY2x1ZGUg
cGFnZS1vdmVydmlldy1mb290ZXIKCQlpbmNsdWRlIHBhZ2Utb3ZlcnZpZXctYnV0dG9ucwoK') );
 insert ignore into ds_pug_templates (name,id,note,template) values ('page-overview-buttons','page-overview-buttons',from_base64('cGFnZS1vdmVydmlldy1idXR0b25z'),from_base64( 'ZGl2LnJvdy5idXR0b25zCglkaXYuY29sCiAgICAJYShocmVmPSIuLz9jb3JyZWN0PTEiKS5idG4u
YnRuLWRhbmdlciAhe2Ntcy5tZCgnYnV0dG9uX2NvcnJlY3RfdmFsaWQnKX0KCWRpdi5jb2wKICAg
IAlpZiBjbXMud21zLnZvdGVyKCkuYmFsbG90cGFwZXIoKS52YWxpZCgpID09PSB0cnVlCgkgICAg
CWEoaHJlZj0iLi8/c2F2ZT0xIikuYnRuLmJ0bi1zdWNjZXNzICF7Y21zLm1kKCdidXR0b25fZmlu
YWxfc2VuZCcpfQo=') );
 insert ignore into ds_pug_templates (name,id,note,template) values ('page-overview-footer','page-overview-footer',from_base64('cGFnZS1vdmVydmlldy1mb290ZXI='),from_base64( 'LSB2YXIgcGx1cmFsX3N1ZmZpeD0oIGNtcy53bXMudm90ZXIoKS5iYWxsb3RwYXBlcigpLm1heCgp
PjE/J19wbHVyYWwnOidfc2luZ3VsYXInICkKLSB2YXIgdGV4dF9rZXk9IiIKaWYgKGNtcy53bXMu
dm90ZXIoKS5iYWxsb3RwYXBlcigpLmNoZWNrY291bnQoKT09MCkKCS0gdGV4dF9rZXkgPSAnemVy
b3ZvdGUnCmVsc2UKCS0gdGV4dF9rZXkgPSAndmFsaWR2b3RlJwppZiBjbXMud21zLnZvdGVyKCku
YmFsbG90cGFwZXIoKS52YWxpZCgpICE9PSB0cnVlCgktIHRleHRfa2V5ID0gJ2ludmFsaWR2b3Rl
JwotIHRleHQgPSBjbXMubWQodGV4dF9rZXkrcGx1cmFsX3N1ZmZpeCkucmVwbGFjZSgiJW1heCIs
IGNtcy53bXMudm90ZXIoKS5iYWxsb3RwYXBlcigpLm1heCgpKS5yZXBsYWNlKCIlY2hlY2tjb3Vu
dCIsIGNtcy53bXMudm90ZXIoKS5iYWxsb3RwYXBlcigpLmNoZWNrY291bnQoKSkKZGl2LnJvdwoJ
ZGl2LmNvbCAhe3RleHR9') );
 insert ignore into ds_pug_templates (name,id,note,template) values ('page-saved','page-saved',from_base64('cGFnZS1zYXZlZA=='),from_base64( 'ZGl2LmNvbnRhaW5lci1mbHVpZAoJZGl2LmNvbnRhaW5lcgoJCWRpdi5yb3cKCQkJZGl2LmNvbCAh
e2Ntcy5tZCgnYmFsbG90cGFwZXJfc2F2ZWQnKX0KCQlkaXYucm93CgkJCWRpdi5jb2wgIXtjbXMu
bWQoJ2JhbGxvdHBhcGVyX3NhdmVkMicpfQo=') );
 insert ignore into ds_pug_templates (name,id,note,template) values ('page-saved-chooseballotpaper','page-saved-chooseballotpaper',from_base64('cGFnZS1zYXZlZC1jaG9vc2ViYWxsb3RwYXBlcg=='),from_base64( 'ZGl2LmNvbnRhaW5lci1mbHVpZAoJZGl2LmNvbnRhaW5lcgoJCWRpdi5yb3cKCQkJZGl2LmNvbCAh
e2Ntcy5tZCgnY2hvb3NlX2JhbGxvdHBhcGVyX3NhdmVkJyl9CgkJZGl2LnJvdwoJCQlkaXYuY29s
ICF7Y21zLm1kKCdjaG9vc2VfYmFsbG90cGFwZXJfc2F2ZWQyJyl9Cg==') );
 insert ignore into ds_pug_templates (name,id,note,template) values ('page-tualocms-bilder','page-tualocms-bilder',from_base64('cGFnZS10dWFsb2Ntcy1iaWxkZXI='),from_base64( 'bWl4aW4gdHVhbG9jbXNiaWxkKGZlbGQsd2VydCxzdHlsZSkKICAgIDpwaHAKICAgICAgICAkaW1h
Z2UgPSBcVHVhbG9cT2ZmaWNlXERTXERTRmlsZXM6Omluc3RhbmNlKCd0dWFsb2Ntc19iaWxkZXIn
KTsKICAgICAgICAkbG9nb2RhdGEgPSAkaW1hZ2UtPmdldEJhc2U2NCgkZmVsZCwkd2VydCx0cnVl
KTsKICAgICAgICAkaW1hZ2VfZXJyb3IgPSAkaW1hZ2UtPmdldEVycm9yKCk7CiAgICBpZiBpbWFn
ZV9lcnJvciE9JycKICAgICAgICBkaXYuY29udGFpbmVyLmFsZXJ0LmFsZXJ0LXdhcm5pbmcKICAg
ICAgICAgICAgZGl2LnJvdwogICAgICAgICAgICAgICAgZGl2LmNvbD1pbWFnZV9lcnJvcgogICAg
ZWxzZQogICAgICAgIGltZyhzcmM9bG9nb2RhdGEsc3R5bGU9c3R5bGUp') );