delimiter ;



insert ignore into ds_pug_templates (name,id,note,template) values ('page','page',from_base64('cGFnZQ=='),from_base64( 'ZXh0ZW5kcyBwYWdlLW1haW4KaW5jbHVkZSBwYWdlLW1peGluLWNoZWNrYm94CmluY2x1ZGUgcGFn
ZS1taXhpbi1iYWxsb3RwYXBlci1tYXgKaW5jbHVkZSBwYWdlLW1peGluLXR1YWxvY21zYmlsZAoK
YmxvY2sgY29udGVudAogICAgaWYgcGFnZS5zZWN0aW9ucwogICAgICAgIGZvciBzZWN0aW9uIGlu
IHBhZ2Uuc2VjdGlvbnMKICAgICAgICAgICAgLSB2YXIgdGVtcGxhdGUgPSBzZWN0aW9uLnRlbXBs
YXRlCiAgICAgICAgICAgIGluY2x1ZGUgcGFnZS1pbmNsdWRlLXNlY3Rpb25zCgogICAgICAgICAg
ICAgICA=') );
 insert ignore into ds_pug_templates (name,id,note,template) values ('page-ballotpaper','page-ballotpaper',from_base64('cGFnZS1iYWxsb3RwYXBlcg=='),from_base64( 'LSB2YXIgZGlzYWJsZWQ9dHJ1ZQotIHZhciBiYWNrZ3JvdW5kX2NvbG9yPSJ2YXIoLS1icy1saWdo
dC10ZXh0KSIKaWYgY21zLndtcy5nZXROZXh0U3RhdGUoKT09J1R1YWxvXE9mZmljZVxPbmxpbmVW
b3RlXFN0YXRlc1xCYWxsb3RwYXBlcicKICAgIC0gZGlzYWJsZWQ9ZmFsc2UKICAgIC0gYmFja2dy
b3VuZF9jb2xvcj1jbXMuYmFsbG90cGFwZXIuZmFyYmUKCmZvcm0ucGFnZS1iYWxsb3RwYXBlci5j
b250YWluZXItZmx1aWQobWV0aG9kPSJwb3N0IikKCWRpdi5jb250YWluZXIKICAgIAlpbmNsdWRl
IHBhZ2UtYmFsbG90cGFwZXItdGl0bGUKCQlkaXYucm93CgkJCWluY2x1ZGUgcGFnZS1iYWxsb3Rw
YXBlci10YWJsZQogICAgICAgIGluY2x1ZGUgcGFnZS1iYWxsb3RwYXBlci1mb290ZXIKCQlpbmNs
dWRlIHBhZ2UtYmFsbG90cGFwZXItYnV0dG9ucwoK') );
 insert ignore into ds_pug_templates (name,id,note,template) values ('page-ballotpaper-buttons','page-ballotpaper-buttons',from_base64('cGFnZS1iYWxsb3RwYXBlci1idXR0b25z'),from_base64( 'ZGl2LnJvdy5idXR0b25zCglkaXYuY29sCgkgICAgaW5wdXQodHlwZT0iaGlkZGVuIixuYW1lPSJz
ZW5kIix2YWx1ZT0iMSIpCiAgICAJYnV0dG9uLmJ0bi5idG4tc3VjY2Vzcyh0eXBlPSJzdWJtaXQi
KSAhe2Ntcy50eHQoJ2JhbGxvdHBhcGVyX3N1Ym1pdF9idXR0b24nKX0K') );
 insert ignore into ds_pug_templates (name,id,note,template) values ('page-ballotpaper-footer','page-ballotpaper-footer',from_base64('cGFnZS1iYWxsb3RwYXBlci1mb290ZXI='),from_base64( 'ZGl2LnJvdwoJLSB2YXIgdGV4dCA9IGNtcy5tYXJrZG93bihjbXMudHh0KCdzdWJtaXRfZmlyc3Qn
KSkKCWRpdi5jb2wgIXt0ZXh0fQ==') );
 insert ignore into ds_pug_templates (name,id,note,template) values ('page-ballotpaper-table','page-ballotpaper-table',from_base64('cGFnZS1iYWxsb3RwYXBlci10YWJsZQ=='),from_base64( 'dGFibGUudGFibGUudGFibGUtc3RyaXBlZAoJdGhlYWQKCQl0cgoJCQl0aChzY29wZT0iY29sIikg
Jm5ic3A7CgkJCXRoLmNoZWNrLmFsaWduLW1pZGRsZShzY29wZT0iY29sIixzdHlsZT0iYmFja2dy
b3VuZC1jb2xvcjoiK2JhY2tncm91bmRfY29sb3IpCiAgICAgICAgICAgIAkrYmFsbG90cGFwZXJt
YXgoY21zLmJhbGxvdHBhcGVyKQoJdGJvZHkKCQllYWNoIGJhbGxvdHBhcGVyX2dyb3VwIGluIGNt
cy5iYWxsb3RwYXBlcl9ncm91cHMKCQkJZWFjaCBjYW5kaWRhdGUgaW4gYmFsbG90cGFwZXJfZ3Jv
dXAuY2FuZGlkYXRlcwoJCQkJdHIKCQkJCQl0ZChzY29wZT0icm93IikKICAgICAgICAgICAgICAg
ICAgICAJaW5jbHVkZSBwYWdlLWJhbGxvdHBhcGVyLXRhYmxlLWNvbnRlbnQKCQkJCQl0ZC5hbGln
bi1taWRkbGUoc2NvcGU9InJvdyIsc3R5bGU9ImJhY2tncm91bmQtY29sb3I6IitiYWNrZ3JvdW5k
X2NvbG9yKQogICAgICAgICAgICAgICAgICAgICAgICArY2hlY2tib3goCiAgICAgICAgICAgICAg
ICAgICAgICAgIAknQicrY21zLndtcy52b3RlcigpLmJhbGxvdHBhcGVyKCkuZ2V0TWFwSGFzaChj
YW5kaWRhdGUuaWQpLAogICAgICAgICAgICAgICAgICAgICAgICAgICAgJ2NhbmRpZGF0ZVtdJywK
ICAgICAgICAgICAgICAgICAgICAgICAgICAgIGNtcy53bXMudm90ZXIoKS5iYWxsb3RwYXBlcigp
LmdldE1hcEhhc2goY2FuZGlkYXRlLmlkKSwKICAgICAgICAgICAgICAgICAgICAgICAgICAgIGNt
cy53bXMudm90ZXIoKS5iYWxsb3RwYXBlcigpLmlzQ2hlY2tlZChjYW5kaWRhdGUuaWQpLAogICAg
ICAgICAgICAgICAgICAgICAgICAgICAgZGlzYWJsZWQKICAgICAgICAgICAgICAgICAgICAgICAg
KQo=') );
 insert ignore into ds_pug_templates (name,id,note,template) values ('page-ballotpaper-table-content','page-ballotpaper-table-content',from_base64('cGFnZS1iYWxsb3RwYXBlci10YWJsZS1jb250ZW50'),from_base64( 'ZWFjaCByb3cgaW4gY21zLnJvd3MKCWRpdihjbGFzcz0icm93Iityb3cucHJlZml4KyIgIityb3cu
cm93X25hbWUpCgkJZWFjaCBjb2wgaW4ganNvbl9kZWNvZGUocm93LmNvbHVtbnMsdHJ1ZSkKCQkJ
ZGl2KGNsYXNzPSJjb2wiK2NvbC5wcmVmaXgrIiAiK2NvbC5jb2x1bW5fbmFtZSkKCQkJCWVhY2gg
ZmllbGQgaW4gY29sLmRlZmluaXRpb24KCQkJCQlpZiBmaWVsZC5odG1sdGFnPT0naW1nJwoJCQkJ
CQlpbWcoCgkJCQkJCQljbGFzcz1maWVsZC5jb2x1bW5fZmllbGQKCQkJCQkJCXN0eWxlPSJib3Jk
ZXItcmFkaXVzOiAxMHB4OyIKCQkJCQkJCXNyYz0iL2ltYWdlcy9wb3J0cmFpdC8iK2NhbmRpZGF0
ZVtmaWVsZC5jb2x1bW5fZmllbGRdKyIucG5nIgoJCQkJCQkpCgkJCQkJZWxzZQoJCQkJCQlwKGNs
YXNzPWZpZWxkLmNvbHVtbl9maWVsZCkgIXtjYW5kaWRhdGVbZmllbGQuY29sdW1uX2ZpZWxkXX0=') );
 insert ignore into ds_pug_templates (name,id,note,template) values ('page-ballotpaper-title','page-ballotpaper-title',from_base64('cGFnZS1iYWxsb3RwYXBlci10aXRsZQ=='),from_base64( 'ZGl2LnJvdwoJZGl2LmNvbAogICAgCS8vIC50ZXh0LWNvbnRvdXIKICAgIAloNChzdHlsZT0iY29s
b3I6IitiYWNrZ3JvdW5kX2NvbG9yKSAhe2Ntcy5iYWxsb3RwYXBlci5uYW1lfQoJCQ==') );
 insert ignore into ds_pug_templates (name,id,note,template) values ('page-chooseballotpaper','page-chooseballotpaper',from_base64('cGFnZS1jaG9vc2ViYWxsb3RwYXBlcg=='),from_base64( 'LXZhciBhdmFpbGFibGVCYWxsb3RwYXBlcnMgPSBjbXMud21zLnZvdGVyKCkuYXZhaWxhYmxlQmFs
bG90cGFwZXJzKCkKLXZhciBncm91cHMgPSBjbXMud21zLnZvdGVyKCkuYXZhaWxhYmxlQmFsbG90
cGFwZXJHcm91cHMoKQotdmFyIGxhc3RJbmRleD0tMQpkaXYucGFnZS1jaG9vc2ViYWxsb3RwYXBl
ci5jb250YWluZXItZmx1aWQKCWRpdi5jb250YWluZXIKCQlkaXYucm93CgkJCWRpdi5jb2wgQml0
dGUgd8OkaGxlbiBTaWUgZWluZW4gU3RpbW16ZXR0ZWwgYXVzLCBmw7xyIHdlbGNoZW4gU2llIGpl
dHp0IGFic3RpbW1lbiBtw7ZjaHRlbi4KZGl2LnBhZ2UtY2hvb3NlYmFsbG90cGFwZXIuY29udGFp
bmVyLWZsdWlkCglkaXYuY29udGFpbmVyCgkJZWFjaCBncm91cCBpbiBncm91cHMKCQkJZGl2LnBh
Z2UtY2hvb3NlYmFsbG90cGFwZXIucm93CgkJCQlkaXYuY29sLWF1dG8KCQkJCQkvLyAudGV4dC1j
b250b3VyCgkJCQkJaDQoc3R5bGU9ImNvbG9yOiIrZ3JvdXAuY29sb3IrIjsiKSAhe2dyb3VwLm5h
bWV9CgkJCQlkaXYuY29sLnRleHQtZW5kCgkJCQkJc3BhbiAoIXtncm91cC5jb3VudH0pCgkJCQkJ
CgkJCWVhY2ggYnAsaW5kZXggaW4gYXZhaWxhYmxlQmFsbG90cGFwZXJzCgkJCQktIHZhciBkYXRh
ID0gYnAuZ2V0Vm90ZXJEYXRhKCk7CgkJCQlpZiBncm91cC5pZCA9PSBicC5nZXRCYWxsb3RwYXBl
cklkKCkKCQkJCQktIGxhc3RJbmRleD1pbmRleDsKCQkJCQlkaXYucm93CgkJCQkJCWRpdi5jb2wt
MQoJCQkJCQlkaXYuY29sCgkJCQkJCQlhKGhyZWY9Ij9iYWxsb3RwYXBlckluZGV4PSIraW5kZXgp
ICF7ZGF0YS5wb3N0X25hbWUyfQoJCQkJCQlkaXYuY29sLTEKCQkJaWYgZ3JvdXAuY291bnQ+MSAg
ICAgICAgICAgICAgICAgICAgICAgIAoJCQkJZGl2LnJvdwoJCQkJCWRpdi5jb2wtMSAmbmJzcDsK
CQkJCQlkaXYuY29sLWF1dG8KCQkJCQkJc3BhbiBVbSBmw7xyIGFsbGUgVW50ZXJuZWhtZW4gbWl0
IGRlbSBTdGltbXpldHRlbCAiIXtncm91cC5uYW1lfSIgaWRlbnRpc2NoIGFienVzdGltbWVuLCBr
bGlja2VuIFNpZSBiaXR0ZSAKCQkJCQkJYShocmVmPSI/Z3JvdXBlZD0xJmJhbGxvdHBhcGVySW5k
ZXg9IitsYXN0SW5kZXgpIGhpZXIgICAgICAgICAgICAKCQkJCQkJc3BhbiAuCgkvLyBkaXYuY29u
dGFpbmVyCgkJZWFjaCBicCBpbiBhdmFpbGFibGVCYWxsb3RwYXBlcnMKCQkJLSB2YXIgZGF0YSA9
IGJwLmdldFZvdGVyRGF0YSgpOwoJCQlkaXYucm93CgkJCQlkaXYuY29sIAoJCQkJCWEoaHJlZj0i
P2JhbGxvdHBhcGVySW5kZXg9IitpbmRleCkKCQkJCQkJaDQgIXticC5nZXRCYWxsb3RwYXBlck5h
bWUoKX0KCQkJCQkJcCAhe2RhdGEucG9zdF9uYW1lMn0KCQkJCQktIGluZGV4ID0gaW5kZXggKzEK
Cg==') );
 insert ignore into ds_pug_templates (name,id,note,template) values ('page-debug','page-debug',from_base64('cGFnZS1kZWJ1Zw=='),from_base64( 'ZGl2LnBhZ2UtZGVidWcuY29udGFpbmVyLWZsdWlkLmFsZXJ0LmFsZXJ0LWRhbmdlcihyb2xlPSJh
bGVydCIpCglkaXYuY29udGFpbmVyCgkJZGl2LnJvdwoJCQlkaXYuY29sLnRleHQtdHJ1bmNhdGUg
TmV4dFN0YXRlICF7Y21zLndtcy5nZXROZXh0U3RhdGUoKX0KCQlkaXYucm93CgkJCWRpdi5jb2wu
dGV4dC10cnVuY2F0ZSBDdXJyZW50U3RhdGUgIXtjbXMud21zLmdldEN1cnJlbnRTdGF0ZSgpfQog
ICAgICAgIGRpdi5yb3cKICAgICAgICAJZGl2LmNvbC50ZXh0LXRydW5jYXRlIFByZXZTdGF0ZSAh
e2Ntcy53bXMuZ2V0UHJldlN0YXRlKCl9Cg==') );
 insert ignore into ds_pug_templates (name,id,note,template) values ('page-documentation','page-documentation',from_base64('cGFnZS1kb2N1bWVudGF0aW9u'),from_base64( 'ZXh0ZW5kcyBwYWdlLW1haW4KaW5jbHVkZSBwYWdlLW1peGluLWNoZWNrYm94CmluY2x1ZGUgcGFn
ZS1taXhpbi1iYWxsb3RwYXBlci1tYXgKCmJsb2NrIGNvbnRlbnQKICAgIGRpdi5jb250YWluZXIt
Zmx1aWQKCSAgICBkaXYuY29udGFpbmVyCiAgICAJICAgIGRpdi5yb3cKICAgICAgICAJICAgIGRp
di5jb2wgIXtjbXMubWFya2Rvd24oY21zLnR4dCgnZG9jdW1lbnRhdGlvbl9ibG9ja18wJykpfQog
ICAgCSAgICBkaXYucm93CiAgICAgICAgCSAgICBkaXYuY29sICF7Y21zLm1hcmtkb3duKGNtcy50
eHQoJ2RvY3VtZW50YXRpb25fYmxvY2tfMScpKX0KICAgIAkgICAgZGl2LnJvdwogICAgICAgIAkg
ICAgZGl2LmNvbCAhe2Ntcy5tYXJrZG93bihjbXMudHh0KCdkb2N1bWVudGF0aW9uX2Jsb2NrXzIn
KSl9CiAgICAJICAgIGRpdi5yb3cKICAgICAgICAJICAgIGRpdi5jb2wgIXtjbXMubWFya2Rvd24o
Y21zLnR4dCgnZG9jdW1lbnRhdGlvbl9ibG9ja18zJykpfQogICAgCSAgICBkaXYucm93CiAgICAg
ICAgCSAgICBkaXYuY29sICF7Y21zLm1hcmtkb3duKGNtcy50eHQoJ2RvY3VtZW50YXRpb25fYmxv
Y2tfNCcpKX0KICAgIAkgICAgZGl2LnJvdwogICAgICAgIAkgICAgZGl2LmNvbCAhe2Ntcy5tYXJr
ZG93bihjbXMudHh0KCdkb2N1bWVudGF0aW9uX2Jsb2NrXzUnKSl9CiAgICAJICAgIGRpdi5yb3cK
ICAgICAgICAJICAgIGRpdi5jb2wgIXtjbXMubWFya2Rvd24oY21zLnR4dCgnZG9jdW1lbnRhdGlv
bl9ibG9ja182JykpfQog') );
 insert ignore into ds_pug_templates (name,id,note,template) values ('page-error','page-error',from_base64('cGFnZS1lcnJvcg=='),from_base64( 'ZGl2LnBhZ2UtZXJyb3IuY29udGFpbmVyLWZsdWlkCglkaXYuY29udGFpbmVyCgkJZGl2LnJvdwoJ
CQlkaXYuY29sIEVzIGlzdCBlaW4gRmVobGVyIHBhc3NpZXJ0IAoJCWRpdi5yb3cKCQkJZGl2LmNv
bCAhe21zZ30K') );
 insert ignore into ds_pug_templates (name,id,note,template) values ('page-footer','page-footer',from_base64('cGFnZS1mb290ZXI='),from_base64( 'OnBocAogICAgJGNtc3BhZ2VsaW5rZSA9IFxUdWFsb1xPZmZpY2VcRFNcRFNUYWJsZTo6aW5zdGFu
Y2UoJ3dtX3BhZ2VfbGlua3MnKS0+bGltaXQoMTAwMDApLT5nZXQoKTsKCmZvb3Rlci5wYWdlLWZv
b3Rlci5jb250YWluZXItZmx1aWQKCWRpdi5jb250YWluZXIKCQlkaXYucm93CiAgICAgICAgICAg
IGRpdi5jb2wtbWQtNAogICAgICAgICAgICAJdWwubWlkLWxpbmtsaXN0KHN0eWxlPSJsaXN0LXN0
eWxlLXR5cGU6IG5vbmU7IG1hcmdpbjogMDsgIHBhZGRpbmc6IDA7IikKCSAgICAgICAgICAgIAll
YWNoIHJlY29yZCBpbiBjbXNwYWdlbGlua2UKICAgICAgICAgICAgICAgICAgICAJaWYgcmVjb3Jk
LmZvb3RlcjE9PTEKCSAgICAJICAgICAgICAgICAgCWxpLmZvb3Rlci1uYXYtaXRlbQogICAgCSAg
ICAgICAgICAgICAgICAgICAgCWEoaHJlZj1yZWNvcmQudXJsLHRhcmdldD1yZWNvcmQudmFydGFy
Z2V0LHJlbD0ibm9vcGVuZXIiKT1yZWNvcmQudGl0bGUKICAgICAgICAgICAgZGl2LmNvbC1tZC00
CiAgICAgICAgICAgIAl1bC5taWQtbGlua2xpc3Qoc3R5bGU9Imxpc3Qtc3R5bGUtdHlwZTogbm9u
ZTsgbWFyZ2luOiAwOyAgcGFkZGluZzogMDsiKQoJICAgICAgICAgICAgCWVhY2ggcmVjb3JkIGlu
IGNtc3BhZ2VsaW5rZQogICAgICAgICAgICAgICAgICAgIAlpZiByZWNvcmQuZm9vdGVyMj09MQoJ
ICAgIAkgICAgICAgICAgICAJbGkuZm9vdGVyLW5hdi1pdGVtCiAgICAJICAgICAgICAgICAgICAg
ICAgICAJYShocmVmPXJlY29yZC51cmwsdGFyZ2V0PXJlY29yZC52YXJ0YXJnZXQscmVsPSJub29w
ZW5lciIpPXJlY29yZC50aXRsZQogICAgICAgICAgICAKICAgICAgICAJZGl2LmNvbC1tZC00CiAg
ICAgICAgICAgIAl1bC5taWQtbGlua2xpc3Qoc3R5bGU9Imxpc3Qtc3R5bGUtdHlwZTogbm9uZTsg
bWFyZ2luOiAwOyAgcGFkZGluZzogMDsiKQoJICAgICAgICAgICAgCWVhY2ggcmVjb3JkIGluIGNt
c3BhZ2VsaW5rZQogICAgICAgICAgICAgICAgICAgIAlpZiByZWNvcmQuZm9vdGVyMz09MQoJICAg
IAkgICAgICAgICAgICAJbGkuZm9vdGVyLW5hdi1pdGVtCiAgICAJICAgICAgICAgICAgICAgICAg
ICAJYShocmVmPXJlY29yZC51cmwsdGFyZ2V0PXJlY29yZC52YXJ0YXJnZXQscmVsPSJub29wZW5l
ciIpPXJlY29yZC50aXRsZQogICAgCWRpdi5yb3cKICAgICAgICAJZGl2LmNvbC50ZXh0LWNlbnRl
cgogICAgICAgICAgICAgIHNwYW4uYnAtZnMtc21hbGwgwqkgIXtjbXMudHh0KCdjb3B5cmlnaHQn
KX0gCg==') );
 insert ignore into ds_pug_templates (name,id,note,template) values ('page-header','page-header',from_base64('cGFnZS1oZWFkZXI='),from_base64( 'aGVhZGVyLnBhZ2UtaGVhZGVyLmNvbnRhaW5lci1mbHVpZAogICAgZGl2LmNvbnRhaW5lcgogICAg
ICAgIGRpdi5yb3cKICAgICAgICAgICAgZGl2LmNvbC1tZC00LnRleHQtc3RhcnQKICAgICAgICAg
ICAgICAgIGEoaHJlZj1jbXMudHh0KCdpaGtfbG9nb19saW5rJyksdGFyZ2V0PSJfYmxhbmsiLHJl
bD0ibm9vcGVuZXIiKQogICAgICAgICAgICAgICAgICAgICt0dWFsb2Ntc2JpbGQoJ3RpdGVsJywn
TG9nbycsJ2hlaWdodDogMi4wY20nKQogICAgICAgICAgICAgICAgICAgIC8vIGltZyhzcmM9Ii9p
bWFnZXMvTG9nb19JSEstS2llbC5zdmciLCBzdHlsZT0iaGVpZ2h0OiAyLjBjbSIpCiAgICAgICAg
ICAgIGRpdi5jb2wtbWQtNC50ZXh0LWNlbnRlcgogICAgICAgICAgICAgICAgYS5kLW5vbmUuZC1t
ZC1pbmxpbmUoaHJlZj1jbXMudHh0KCd3YWhsX2xvZ29fbGluaycpLHRhcmdldD0iX2JsYW5rIixy
ZWw9Im5vb3BlbmVyIikKICAgICAgICAgICAgICAgIAkrdHVhbG9jbXNiaWxkKCd0aXRlbCcsJ1dh
aGxsb2dvJywnJykKICAgICAgICAgICAgZGl2LmNvbC1tZC00LnRleHQtZW5kCiAgICAgICAgICAg
ICAgICBkaXYucm93CiAgICAgICAgICAgICAgICAgICAgZGl2LmNvbAogICAgICAgICAgICAgICAg
ICAgICAgICBhKGhyZWY9InRlbDoiK2Ntcy50eHQoJ2hlYWRlcl90ZWxlZm9uX2xpbmsnKSkKICAg
ICAgICAgICAgICAgICAgICAgICAgICAgIGkuZmFyLmZhLXBob25lLWFsdAogICAgICAgICAgICAg
ICAgICAgICAgICAgICAgICAgIHNwYW4uZC1ub25lLmQtc20taW5saW5lICZuYnNwOyZuYnNwOyF7
Y21zLnR4dCgnaGVhZGVyX3RlbGVmb25fdGV4dCcpfSAKICAgICAgICAgICAgICAgIC1pZiAoY21z
Lndtcy52b3RlcigpLmlzTG9nZ2VkSW4oKSA9PSB0cnVlICkKICAgICAgICAgICAgICAgICAgICBk
aXYucm93CiAgICAgICAgICAgICAgICAgICAgICAgIGRpdi5jb2wKICAgICAgICAgICAgICAgICAg
ICAgICAgICAgIGEuYnRuLmJ0bi1wcmltYXJ5KGhyZWY9Ii4vP2xvZ291dD0xIixyZWw9Im5vb3Bl
bmVyIiApICF7Y21zLnR4dCgnYnV0dG9uX2xvZ291dCcpfQpkaXYuY29udGFpbmVyLWZsdWlkLmJn
LXByaW1hcnkKICAgIGRpdi5jb2wudGV4dC1jZW50ZXIKICAgICAgICBzcGFuICF7Y21zLnR4dCgn
bG9naW5mb3JtX2xpZ2h0X2xpbmUnKX0gCiAgICAgICAgaWYgY21zLnR4dCgnbG9naW5mb3JtX2Rh
cmtfbGluZScpLmxlbmd0aCA+IDEKICAgICAgICAgICAgYnIKICAgICAgICAgICAgc3BhbihzdHls
ZT0iZm9udC13ZWlnaHQ6IExpZ2h0ZXN0OyIpICF7Y21zLnR4dCgnbG9naW5mb3JtX2RhcmtfbGlu
ZScpfSA=') );
 insert ignore into ds_pug_templates (name,id,note,template) values ('page-include-sections','page-include-sections',from_base64('cGFnZS1pbmNsdWRlLXNlY3Rpb25z'),from_base64( 'Y2FzZSB0ZW1wbGF0ZQogICAgd2hlbiAncGFnZS1zZWN0aW9uJwogICAgICAgIGluY2x1ZGUgcGFn
ZS1zZWN0aW9uCiAgICB3aGVuICdwYWdlLW9ubGluZXZvdGUnCiAgICAgICAgaW5jbHVkZSBwYWdl
LW9ubGluZXZvdGUKICAgIGRlZmF1bHQKICAgICAgICBzcGFuICF7dGVtcGxhdGV9IGV4aXN0aWVy
dCBuaWNodAo=') );
 insert ignore into ds_pug_templates (name,id,note,template) values ('page-legitimation','page-legitimation',from_base64('cGFnZS1sZWdpdGltYXRpb24='),from_base64( 'ZGl2LnBhZ2UtbGVnaXRpbWF0aW9uLmNvbnRhaW5lci1mbHVpZAoJZGl2LmNvbnRhaW5lcgoJCWRp
di5yb3cKCQkJZGl2LmNvbCAhe2Ntcy5tYXJrZG93bihjbXMudHh0KCdsZWdpdGltYXRpb24nKSl9
CmRpdi5jb250YWluZXItZmx1aWQKICAgIGRpdi5jb250YWluZXIKICAgIAlkaXYucm93CiAgICAg
ICAgCWZvcm0uY29sKG1ldGhvZD0icG9zdCIsYWN0aW9uPSIuLyIpCiAgICAgICAgICAgIAlpbnB1
dCgKICAgICAgICAgIAkJCXR5cGU9ImhpZGRlbiIsCgkJCSAgICAgICAgbmFtZT0ibG9nb3V0IiwK
CQkJICAgICAgICB2YWx1ZT0xCgkJCSAgICApCiAgICAgICAgICAgICAgICBidXR0b24uYnRuLmJ0
bi13YXJuaW5nICF7Y21zLm1hcmtkb3duKGNtcy50eHQoJ2xlZ2l0aW1hdGlvbl9ubycpKX0KICAg
ICAgICAJZm9ybS5jb2wobWV0aG9kPSJwb3N0IixhY3Rpb249Ii4vIikKICAgICAgICAgICAgCWlu
cHV0KAogICAgICAgICAgCQkJdHlwZT0iaGlkZGVuIiwKCQkJICAgICAgICBuYW1lPSJsZWdpdGlt
YXRpb24iLAoJCQkgICAgICAgIHZhbHVlPWNtcy5sZWdpdGltYXRpb25fdXVpZAoJCQkgICAgKQog
ICAgICAgICAgICAgICAgaW5wdXQoCiAgICAgICAgICAJCQl0eXBlPSJoaWRkZW4iLAoJCQkgICAg
ICAgIG5hbWU9ImxlZ2l0aW1hdGlvbl9jb25maXJtZWQiLAoJCQkgICAgICAgIHZhbHVlPTEKCQkJ
ICAgICkKICAgICAgICAgICAgICAgIGJ1dHRvbi5idG4uYnRuLXN1Y2Nlc3MgIXtjbXMubWFya2Rv
d24oY21zLnR4dCgnbGVnaXRpbWF0aW9uX3llcycpKX0KaW5jbHVkZSBwYWdlLWxlZ2l0aW1hdGlv
bi1zdWJ0ZXh0Cg==') );
 insert ignore into ds_pug_templates (name,id,note,template) values ('page-legitimation-subtext','page-legitimation-subtext',from_base64('cGFnZS1sZWdpdGltYXRpb24tc3VidGV4dA=='),from_base64( 'ZGl2LmNvbnRhaW5lci1mbHVpZC5wYWdlLWxlZ2l0aW1hdGlvbi1zdWJ0ZXh0CglkaXYuY29udGFp
bmVyCgkJZGl2LnJvdwogICAgICAgIAlkaXYuY29sLmxlZ2l0aW1hdGlvbiAhe2Ntcy5tYXJrZG93
bihjbXMudHh0KCdsZWdpdGltYXRpb25fc3VidGV4dCcpKX0K') );
 insert ignore into ds_pug_templates (name,id,note,template) values ('page-login','page-login',from_base64('cGFnZS1sb2dpbg=='),from_base64( 'Zm9ybS5wYWdlLWxvZ2luLmNvbnRhaW5lci1mbHVpZChtZXRob2Q9InBvc3QiLGFjdGlvbj0iLi8i
KQoJZGl2LmNvbnRhaW5lcgoJCWRpdi5yb3cuYWxlcnQuYWxlcnQtcHJpbWFyeQogICAgCQlkaXYu
Y29sICF7Y21zLm1hcmtkb3duKGNtcy50eHQoJ2xvZ2luZm9ybV93ZWxsY29tZV90ZXh0JykpfQoJ
CWRpdi5yb3cKICAgIAkJZGl2LmNvbCAhe2Ntcy5tYXJrZG93bihjbXMudHh0KCdsb2dpbmZvcm1f
c2VjdXJpdHknKSl9IAoJCWRpdi5yb3cKICAgIAkJZGl2LmNvbAogICAgICAgIAkJaW5jbHVkZSBw
YWdlLWxvZ2luLWZvcm0K') );
 insert ignore into ds_pug_templates (name,id,note,template) values ('page-login-form','page-login-form',from_base64('cGFnZS1sb2dpbi1mb3Jt'),from_base64( 'LXZhciBwYXR0ZXJuPSJbQUJDREVGR0hKS0xNTlBSU1RVVlhZWmFiY2RlZmdoaWprbXBzdHV2eHl6
MDEyMzQ1Njc4OV17OH0iCmlucHV0LmhpbnQtY2lyY2xlLWNoZWNrYm94KAogIGlkPSdsb2dpbnRy
aWdnZXInCiAgbmFtZT0nYWNjZXB0JwogIHR5cGU9ImNoZWNrYm94IgogIGNoZWNrZWQ9ZmFsc2UK
ICBkaXNhYmxlZD1mYWxzZQogIHJlcXVpcmVkPXRydWUKKQpsYWJlbC5jb250YWluZXIoIGZvcj0n
bG9naW50cmlnZ2VyJyApCglkaXYucm93CgkJZGl2LmNvbC1hdXRvCiAgICAJCWkuZmEuZmEtdGlt
ZXMKCQlkaXYuY29sICF7Y21zLm1hcmtkb3duKGNtcy50eHQoJ2xvZ2luZm9ybV9ib3hoaW53ZWlz
JykpfQogICAgCQpkaXYuZm9ybWJveAogICAgZGl2LmZvcm0tZ3JvdXAKICAgICAgICBsYWJlbChm
b3I9InAxIikgTG9naW4KICAgICAgICBpbnB1dC5mb3JtLWNvbnRyb2wuY29sKAogICAgICAgIAl0
eXBlPSJ0ZXh0IiwKICAgICAgICAgICAgcGF0dGVybj1wYXR0ZXJuLAogICAgICAgICAgICBwbGFj
ZWhvbGRlcj0iTG9naW4iLAogICAgICAgICAgICBtYXhsZW5ndGg9IjgiLAogICAgICAgICAgICBu
YW1lPWNtcy53bXMudXNlcm5hbWVmaWVsZCgpLAogICAgICAgICAgICBpZD0icDEiLAogICAgICAg
ICAgICByZXF1aXJlZD0idHJ1ZSIsCiAgICAgICAgICAgIHRpdGxlPWNtcy50eHQoJ2Zvcm1faW5w
dXRfdGl0bGUnKSwKICAgICAgICAgICAgdmFsdWU9Y21zLnAxCiAgICAgICAgKQogICAgZGl2LmZv
cm0tZ3JvdXAoc3R5bGU9Im1hcmdpbi1ib3R0b206IDEwcHg7IikKICAgICAgICBsYWJlbChmb3I9
InAyIikgUGFzc3dvcnQKICAgICAgICBpbnB1dC5mb3JtLWNvbnRyb2wuY29sKAogICAgICAgIAl0
eXBlPSJwYXNzd29yZCIsCiAgICAgICAgICAgIHBhdHRlcm49cGF0dGVybiwKICAgICAgICAgICAg
cGxhY2Vob2xkZXI9IlBhc3N3b3J0IiwKICAgICAgICAgICAgbWF4bGVuZ3RoPSI4IiwKICAgICAg
ICAgICAgbmFtZT1jbXMud21zLnBhc3N3b3JkZmllbGQoKSwKICAgICAgICAgICAgaWQ9InAyIiwK
ICAgICAgICAgICAgcmVxdWlyZWQ9InRydWUiLAogICAgICAgICAgICB0aXRsZT1jbXMudHh0KCdm
b3JtX2lucHV0X3RpdGxlJyksCiAgICAgICAgICAgIHZhbHVlPWNtcy5wMgogICAgICAgICkKCiAg
ICBicgogICAgCiAgICBkaXYjY29va2llRGl2LnJvdyhzdHlsZT0iZGlzcGxheTpub25lOyIpCiAg
ICAgICAgZGl2LmNvbCAhe2Ntcy5tYXJrZG93bihjbXMudHh0KCdjb29raWVfdGV4dCcpKX0KICAg
IAogICAgZGl2LnJvdwogICAgICAgIGRpdi5jb2wKICAgICAgICAgICAgYnV0dG9uLmJ0bi5idG4t
c3VjY2Vzcyh0eXBlPSJzdWJtaXQiKSAhe2Ntcy5tYXJrZG93bihjbXMudHh0KCdidXR0b25fbG9n
aW4nKSl9') );
 insert ignore into ds_pug_templates (name,id,note,template) values ('page-logout','page-logout',from_base64('cGFnZS1sb2dvdXQ='),from_base64( 'ZGl2LnBhZ2UtbG9nb3V0LmNvbnRhaW5lci1mbHVpZAoJZGl2LmNvbnRhaW5lcgoJCWRpdi5yb3cK
CQkJZGl2LmNvbCAhe2Ntcy5tYXJrZG93bihjbXMudHh0KCdhc2tsb2dvdXRfdGV4dCcpKX0KCQlk
aXYucm93CgkJCWRpdi5jb2wKICAgICAgICAgICAgCWEuYnRuLmJ0bi1pbmZvKAogICAgICAgICAg
ICAgICAgCWhyZWY9Ii4vP2xvZ291dF9jb25maXJtZWQ9MSIsCiAgICAgICAgICAgICAgICAgICAg
cmVsPSJub29wZW5lciIKICAgICAgICAgICAgICAgICkgIXtjbXMudHh0KCdhc2tsb2dvdXRfYnV0
dG9uX2xvZ291dCcpfQoJCQlkaXYuY29sCiAgICAgICAgICAgIAlhLmJ0bi5idG4taW5mbygKICAg
ICAgICAgICAgICAgIAlocmVmPSIuLz9sb2dvdXRfY2FuY2VsZWQ9MSIsCiAgICAgICAgICAgICAg
ICAgICAgcmVsPSJub29wZW5lciIKICAgICAgICAgICAgICAgICkgIXtjbXMudHh0KCdhc2tsb2dv
dXRfYnV0dG9uX2JhY2snKX0K') );
 insert ignore into ds_pug_templates (name,id,note,template) values ('page-main','page-main',from_base64('cGFnZS1tYWlu'),from_base64( 'Lgpkb2N0eXBlIGh0bWwKaHRtbChsYW5nPSdkZScpCiAgICBoZWFkCiAgICAgICAgYmxvY2sgaGVh
ZAogICAgICAgICAgICBtZXRhKGNoYXJzZXQ9J3V0Zi04JykKCQkJbWV0YShuYW1lPSJmb3JtYXQt
ZGV0ZWN0aW9uIixjb250ZW50PSJ0ZWxlcGhvbmU9bm8iKQogICAgICAgICAgICBtZXRhKG5hbWU9
InZpZXdwb3J0Iixjb250ZW50PSJ3aWR0aD1kZXZpY2Utd2lkdGgsIGluaXRpYWwtc2NhbGU9MSwg
c2hyaW5rLXRvLWZpdD1ubyIpCiAgICAgICAgICAgIHRpdGxlICF7Y21zLnR4dCgnc2l0ZV90aXRs
ZScpfQoJCQlsaW5rKAogICAgICAgICAgICAJaHJlZj0iLi9ib290c3RyYXBidWlsZC9ib290c3Ry
YXAubWluLmNzcyIgCiAgICAgICAgICAgICAgICByZWw9InN0eWxlc2hlZXQiIAogICAgICAgICAg
ICAgICAgCiAgICAgICAgICAgICkKICAgICAgICAgICAgbGluayhyZWw9InN0eWxlc2hlZXQiLGhy
ZWY9Ii4vZm9udGF3ZXNvbWUvZnJlZS9jc3MvYWxsLm1pbi5jc3MiKQogICAgICAgICAgICBsaW5r
KHJlbD0ic3R5bGVzaGVldCIsaHJlZj0iLi9wYWdlLmNzcyIpCiAgICAgICAgICAgIC8vc2NyaXB0
KHR5cGU9InRleHQvamF2YXNjcmlwdCIsc3JjPSIvanMvY29va2llLWNoZWNrLmpzIixkZWZlcikK
CWJvZHkodGFiSW5kZXg9MCkKICAgIAlpbmNsdWRlIHBhZ2UtaGVhZGVyCiAgICAJYmxvY2sgY29u
dGVudAogICAgICAgIGluY2x1ZGUgcGFnZS1kZWJ1ZwogICAgICAgIGluY2x1ZGUgcGFnZS1mb290
ZXI=') );
 insert ignore into ds_pug_templates (name,id,note,template) values ('page-maintenance','page-maintenance',from_base64('cGFnZS1tYWludGVuYW5jZQ=='),from_base64( 'ZGl2LnBhZ2UtbWFpbnRlbmFuY2UuY29udGFpbmVyLWZsdWlkCglkaXYuY29udGFpbmVyCgkJZGl2
LnJvdwoJCQlkaXYuY29sICF7Y21zLm1hcmtkb3duKGNtcy50eHQoJ21haW50ZW5hbmNlJykpfQo=') );
 insert ignore into ds_pug_templates (name,id,note,template) values ('page-mixin-ballotpaper-max','page-mixin-ballotpaper-max',from_base64('cGFnZS1taXhpbi1iYWxsb3RwYXBlci1tYXg='),from_base64( 'bWl4aW4gYmFsbG90cGFwZXJtYXgoYmFsbG90cGFwZXIpCgktIHZhciBrcmV1enRleHQ9J0tyZXV6
JwoJLSBpZiAoYmFsbG90cGFwZXIuc2l0emUgPiAxKQoJCS0ga3JldXp0ZXh0PSdLcmV1emUnCglk
aXYucm93LmFsaWduLW1pZGRsZS50ZXh0LWNlbnRlcgoJCXNwYW4gTWF4LgoJCWJyCgkJc3BhbiAh
e2JhbGxvdHBhcGVyLnNpdHplfQoJCWJyCgkJc3BhbiAhe2tyZXV6dGV4dH0K') );
 insert ignore into ds_pug_templates (name,id,note,template) values ('page-mixin-checkbox','page-mixin-checkbox',from_base64('cGFnZS1taXhpbi1jaGVja2JveA=='),from_base64( 'bWl4aW4gY2hlY2tib3goaWQsIG5hbWUsIHZhbHVlLCBjaGVja2VkLCBkaXNhYmxlZCwgcmVxdWly
ZWQsIGhpbnQpCiAgICBpbnB1dC5jaXJjbGUtY2hlY2tib3goCiAgICAgICAgaWQ9aWQKICAgICAg
ICBuYW1lPW5hbWUKICAgICAgICB2YWx1ZT12YWx1ZQogICAgICAgIHR5cGU9ImNoZWNrYm94Igog
ICAgICAgIGNoZWNrZWQ9Y2hlY2tlZAogICAgICAgIGRpc2FibGVkPWRpc2FibGVkCiAgICAgICAg
cmVxdWlyZWQ9cmVxdWlyZWQKICAgICkKICAgIGxhYmVsKCBmb3I9aWQgKQogICAgCWRpdgogICAg
ICAgIAlpLmZhLmZhLXRpbWVzCiAgICAgICAgc3BhbiAhe2hpbnR9Cg==') );
 insert ignore into ds_pug_templates (name,id,note,template) values ('page-mixin-tualocmsbild','page-mixin-tualocmsbild',from_base64('cGFnZS1taXhpbi10dWFsb2Ntc2JpbGQ='),from_base64( 'bWl4aW4gdHVhbG9jbXNiaWxkKGZlbGQsd2VydCxzdHlsZSkKICAgIDpwaHAKICAgICAgICAkaW1h
Z2UgPSBcVHVhbG9cT2ZmaWNlXERTXERTRmlsZXM6Omluc3RhbmNlKCd0dWFsb2Ntc19iaWxkZXIn
KTsKICAgICAgICAkbG9nb2RhdGEgPSAkaW1hZ2UtPmdldEJhc2U2NCgkZmVsZCwkd2VydCx0cnVl
KTsKICAgICAgICAkaW1hZ2VfZXJyb3IgPSAkaW1hZ2UtPmdldEVycm9yKCk7CiAgICBpZiBpbWFn
ZV9lcnJvciE9JycKICAgICAgICBkaXYuY29udGFpbmVyLmFsZXJ0LmFsZXJ0LXdhcm5pbmcKICAg
ICAgICAgICAgZGl2LnJvdwogICAgICAgICAgICAgICAgZGl2LmNvbD1pbWFnZV9lcnJvcgogICAg
ZWxzZQogICAgICAgIGltZyhzcmM9bG9nb2RhdGEsc3R5bGU9c3R5bGUp') );
 insert ignore into ds_pug_templates (name,id,note,template) values ('page-onlinevote','page-onlinevote',from_base64('cGFnZS1vbmxpbmV2b3Rl'),from_base64( 'Y2FzZSBjbXMud21zLmdldE5leHRTdGF0ZSgpCiAgICB3aGVuICdUdWFsb1xPZmZpY2VcT25saW5l
Vm90ZVxTdGF0ZXNcTG9naW4nCiAgICAgICAgaW5jbHVkZSBwYWdlLWxvZ2luCiAgICB3aGVuICdU
dWFsb1xPZmZpY2VcT25saW5lVm90ZVxTdGF0ZXNcTGVnaXRpbWF0aW9uJwogICAgICAgIGluY2x1
ZGUgcGFnZS1sZWdpdGltYXRpb24KICAgIHdoZW4gJ1R1YWxvXE9mZmljZVxPbmxpbmVWb3RlXFN0
YXRlc1xMb2dvdXQnCiAgICAgICAgaW5jbHVkZSBwYWdlLWxvZ291dAogICAgd2hlbiAnVHVhbG9c
T2ZmaWNlXE9ubGluZVZvdGVcU3RhdGVzXENob29zZUJhbGxvdHBhcGVyJwogICAgICAgIGluY2x1
ZGUgcGFnZS1jaG9vc2ViYWxsb3RwYXBlcgogICAgd2hlbiAnVHVhbG9cT2ZmaWNlXE9ubGluZVZv
dGVcU3RhdGVzXEJhbGxvdHBhcGVyJwogICAgICAgIGluY2x1ZGUgcGFnZS1iYWxsb3RwYXBlcgog
ICAgd2hlbiAnVHVhbG9cT2ZmaWNlXE9ubGluZVZvdGVcU3RhdGVzXEJhbGxvdHBhcGVyT3ZlcnZp
ZXcnCiAgICAgICAgaW5jbHVkZSBwYWdlLW92ZXJ2aWV3CiAgICB3aGVuICdUdWFsb1xPZmZpY2Vc
T25saW5lVm90ZVxTdGF0ZXNcU2F2ZUNvbXBsZXRlZENob29zZUJhbGxvdHBhcGVyJwogICAgICAg
IGluY2x1ZGUgcGFnZS1zYXZlZC1jaG9vc2ViYWxsb3RwYXBlcgogICAgICAgIGluY2x1ZGUgcGFn
ZS1jaG9vc2ViYWxsb3RwYXBlcgogICAgd2hlbiAnVHVhbG9cT2ZmaWNlXE9ubGluZVZvdGVcU3Rh
dGVzXExvZ2luQWxscmVhZHlWb3RlZEVycm9yJwogICAgICAgIC12YXIgbXNnID0gIkbDvHIgZGll
c2VuIFN0aW1temV0dGVsIHd1cmRlIGJlcmVpdHMgZ2V3w6RobHQuIgogICAgICAgIGluY2x1ZGUg
cGFnZS1lcnJvcgogICAgd2hlbiAnVHVhbG9cT2ZmaWNlXE9ubGluZVZvdGVcU3RhdGVzXFNhdmVD
b21wbGV0ZWQnCiAgICAgICAgaW5jbHVkZSBwYWdlLXNhdmVkCiAgICB3aGVuICdUdWFsb1xPZmZp
Y2VcT25saW5lVm90ZVxTdGF0ZXNcRXJyb3InCiAgICAgICAgaW5jbHVkZSBwYWdlLWVycm9yCiAg
ICB3aGVuICdUdWFsb1xPZmZpY2VcT25saW5lVm90ZVxTdGF0ZXNcQmFsbG90UGFwZXJBbGxyZWFk
eVZvdGVkRXJyb3InCiAgICAgICAgLXZhciBtc2cgPSAiRsO8ciBkaWVzZW4gU3RpbW16ZXR0ZWwg
d3VyZGUgYmVyZWl0cyBnZXfDpGhsdC4iCiAgICAgICAgaW5jbHVkZSBwYWdlLWVycm9yCiAgICB3
aGVuICdUdWFsb1xPZmZpY2VcT25saW5lVm90ZVxTdGF0ZXNcU2Vzc2lvbkludmFsaWRFcnJvcicK
ICAgICAgICAtdmFyIG1zZyA9ICJJaHJlIFNpdHp1bmcgaXN0IGFiZ2VsYXVmZW4uIgogICAgICAg
IGluY2x1ZGUgcGFnZS1lcnJvcgogICAgd2hlbiAnVHVhbG9cT2ZmaWNlXE9ubGluZVZvdGVcU3Rh
dGVzXFNlc3Npb25CYWxsb3RwYXBlclNhdmVFcnJvcicKICAgICAgICAtdmFyIG1zZyA9ICJFcyBn
aWJ0IGJlcmVpdHMgZWluZSB3ZWl0ZXJlIEFubWVsZHVuZy4iCiAgICAgICAgaW5jbHVkZSBwYWdl
LWVycm9yCiAgICBkZWZhdWx0CiAgICAgICAgaW5jbHVkZSBwYWdlLW1haW50ZW5hbmNlCiAgICAg
ICAgICAgIA==') );
 insert ignore into ds_pug_templates (name,id,note,template) values ('page-overview','page-overview',from_base64('cGFnZS1vdmVydmlldw=='),from_base64( 'LSB2YXIga3JldXp0ZXh0PSdLcmV1eicKLSB2YXIgZGlzYWJsZWQ9dHJ1ZQotIHZhciBiYWNrZ3Jv
dW5kX2NvbG9yPSJ2YXIoLS1icy1saWdodC10ZXh0KSIKLSBpZiAoY21zLmJhbGxvdHBhcGVyLnNp
dHplID4gMSkKCS0ga3JldXp0ZXh0PSdLcmV1emUnCmZvcm0ucGFnZS1iYWxsb3RwYXBlci5jb250
YWluZXItZmx1aWQKCWRpdi5jb250YWluZXIKCQlpbmNsdWRlIHBhZ2UtYmFsbG90cGFwZXItdGl0
bGUKCQlkaXYucm93CgkJCWluY2x1ZGUgcGFnZS1iYWxsb3RwYXBlci10YWJsZQoJCWluY2x1ZGUg
cGFnZS1vdmVydmlldy1mb290ZXIKCQlpbmNsdWRlIHBhZ2Utb3ZlcnZpZXctYnV0dG9ucwoK') );
 insert ignore into ds_pug_templates (name,id,note,template) values ('page-overview-buttons','page-overview-buttons',from_base64('cGFnZS1vdmVydmlldy1idXR0b25z'),from_base64( 'ZGl2LnJvdy5idXR0b25zCglkaXYuY29sCiAgICAJYShocmVmPSIuLz9jb3JyZWN0PTEiKS5idG4u
YnRuLWRhbmdlciAhe2Ntcy5tYXJrZG93bihjbXMudHh0KCdidXR0b25fY29ycmVjdF92YWxpZCcp
KX0KCWRpdi5jb2wKICAgIAlpZiBjbXMud21zLnZvdGVyKCkuYmFsbG90cGFwZXIoKS52YWxpZCgp
ID09PSB0cnVlCgkgICAgCWEoaHJlZj0iLi8/c2F2ZT0xIikuYnRuLmJ0bi1zdWNjZXNzICF7Y21z
Lm1hcmtkb3duKGNtcy50eHQoJ2J1dHRvbl9maW5hbF9zZW5kJykpfQo=') );
 insert ignore into ds_pug_templates (name,id,note,template) values ('page-overview-footer','page-overview-footer',from_base64('cGFnZS1vdmVydmlldy1mb290ZXI='),from_base64( 'LSB2YXIgcGx1cmFsX3N1ZmZpeD0oIGNtcy53bXMudm90ZXIoKS5iYWxsb3RwYXBlcigpLm1heCgp
PjE/J19wbHVyYWwnOidfc2luZ3VsYXInICkKLSB2YXIgdGV4dF9rZXk9IiIKaWYgKGNtcy53bXMu
dm90ZXIoKS5iYWxsb3RwYXBlcigpLmNoZWNrY291bnQoKT09MCkKCS0gdGV4dF9rZXkgPSAnemVy
b3ZvdGUnCmVsc2UKCS0gdGV4dF9rZXkgPSAndmFsaWR2b3RlJwppZiBjbXMud21zLnZvdGVyKCku
YmFsbG90cGFwZXIoKS52YWxpZCgpICE9PSB0cnVlCgktIHRleHRfa2V5ID0gJ2ludmFsaWR2b3Rl
JwotIHRleHQgPSBjbXMubWFya2Rvd24oY21zLnR4dCh0ZXh0X2tleStwbHVyYWxfc3VmZml4KS5y
ZXBsYWNlKCIlbWF4IiwgY21zLndtcy52b3RlcigpLmJhbGxvdHBhcGVyKCkubWF4KCkpLnJlcGxh
Y2UoIiVjaGVja2NvdW50IiwgY21zLndtcy52b3RlcigpLmJhbGxvdHBhcGVyKCkuY2hlY2tjb3Vu
dCgpKSkKZGl2LnJvdwoJZGl2LmNvbCAhe3RleHR9') );
 insert ignore into ds_pug_templates (name,id,note,template) values ('page-saved','page-saved',from_base64('cGFnZS1zYXZlZA=='),from_base64( 'ZGl2LmNvbnRhaW5lci1mbHVpZAoJZGl2LmNvbnRhaW5lcgoJCWRpdi5yb3cKCQkJZGl2LmNvbCAh
e2Ntcy5tYXJrZG93bihjbXMudHh0KCdiYWxsb3RwYXBlcl9zYXZlZCcpKX0KCQlkaXYucm93CgkJ
CWRpdi5jb2wgIXtjbXMubWFya2Rvd24oY21zLnR4dCgnYmFsbG90cGFwZXJfc2F2ZWQyJykpfQo=') );
 insert ignore into ds_pug_templates (name,id,note,template) values ('page-saved-chooseballotpaper','page-saved-chooseballotpaper',from_base64('cGFnZS1zYXZlZC1jaG9vc2ViYWxsb3RwYXBlcg=='),from_base64( 'ZGl2LmNvbnRhaW5lci1mbHVpZAoJZGl2LmNvbnRhaW5lcgoJCWRpdi5yb3cKCQkJZGl2LmNvbCAh
e2Ntcy5tYXJrZG93bihjbXMudHh0KCdjaG9vc2VfYmFsbG90cGFwZXJfc2F2ZWQnKSl9CgkJZGl2
LnJvdwoJCQlkaXYuY29sICF7Y21zLm1hcmtkb3duKGNtcy50eHQoJ2Nob29zZV9iYWxsb3RwYXBl
cl9zYXZlZDInKSl9Cg==') );
 insert ignore into ds_pug_templates (name,id,note,template) values ('page-section','page-section',from_base64('cGFnZS1zZWN0aW9u'),from_base64( 'ZGl2LmNvbnRhaW5lci1mbHVpZAogICAgZGl2LmNvbnRhaW5lcgogICAgICAgIGRpdi5yb3cKICAg
ICAgICAgICAgZGl2LmNvbAogICAgICAgICAgICAgICAgaDMgIXtzZWN0aW9uLnRpdGxlfQogICAg
ICAgICAgICAgICAgcCAhe2Ntcy5tYXJrZG93bihzZWN0aW9uLmNvbnRlbnQpfQ==') );