DELIMITER;

INSERT INTO
    `ds` (
        `table_name`,
        `title`,
        `reorderfield`,
        `use_history`,
        `searchfield`,
        `displayfield`,
        `sortfield`,
        `searchany`,
        `hint`,
        `overview_tpl`,
        `sync_table`,
        `writetable`,
        `globalsearch`,
        `listselectionmodel`,
        `sync_view`,
        `syncable`,
        `cssstyle`,
        `read_table`,
        `existsreal`,
        `class_name`,
        `special_add_panel`,
        `read_filter`,
        `listxtypeprefix`,
        `phpexporter`,
        `phpexporterfilename`,
        `combined`,
        `allowForm`,
        `alternativeformxtype`,
        `character_set_name`,
        `default_pagesize`,
        `listviewbaseclass`,
        `showactionbtn`
    )
VALUES
    (
        'pgpkeys',
        'Digitale Wahlurne',
        '',
        0,
        'keyid',
        'keyid',
        'keyname',
        1,
        '',
        '',
        '',
        '',
        0,
        'tualomultirowmodel',
        '',
        0,
        '',
        'view_readtable_pgpkeys',
        1,
        'Wahlsystem',
        '',
        '',
        'listview',
        'XlsxWriter',
        '{GUID}',
        0,
        1,
        '',
        '',
        100,
        'Tualo.DataSets.ListView',
        1
    ) ON DUPLICATE KEY
UPDATE
    title =
VALUES
(title),
    reorderfield =
VALUES
(reorderfield),
    use_history =
VALUES
(use_history),
    searchfield =
VALUES
(searchfield),
    displayfield =
VALUES
(displayfield),
    sortfield =
VALUES
(sortfield),
    searchany =
VALUES
(searchany),
    hint =
VALUES
(hint),
    overview_tpl =
VALUES
(overview_tpl),
    sync_table =
VALUES
(sync_table),
    writetable =
VALUES
(writetable),
    globalsearch =
VALUES
(globalsearch),
    listselectionmodel =
VALUES
(listselectionmodel),
    sync_view =
VALUES
(sync_view),
    syncable =
VALUES
(syncable),
    cssstyle =
VALUES
(cssstyle),
    alternativeformxtype =
VALUES
(alternativeformxtype),
    read_table =
VALUES
(read_table),
    class_name =
VALUES
(class_name),
    special_add_panel =
VALUES
(special_add_panel),
    existsreal =
VALUES
(existsreal),
    character_set_name =
VALUES
(character_set_name),
    read_filter =
VALUES
(read_filter),
    listxtypeprefix =
VALUES
(listxtypeprefix),
    phpexporter =
VALUES
(phpexporter),
    phpexporterfilename =
VALUES
(phpexporterfilename),
    combined =
VALUES
(combined),
    default_pagesize =
VALUES
(default_pagesize),
    allowForm =
VALUES
(allowForm),
    listviewbaseclass =
VALUES
(listviewbaseclass),
    showactionbtn =
VALUES
(showactionbtn),
    modelbaseclass =
VALUES
(modelbaseclass);

INSERT
    IGNORE INTO `ds_column` (
        `table_name`,
        `column_name`,
        `default_value`,
        `default_max_value`,
        `default_min_value`,
        `is_primary`,
        `update_value`,
        `is_nullable`,
        `is_referenced`,
        `referenced_table`,
        `referenced_column_name`,
        `data_type`,
        `column_key`,
        `column_type`,
        `character_maximum_length`,
        `numeric_precision`,
        `numeric_scale`,
        `character_set_name`,
        `privileges`,
        `existsreal`,
        `deferedload`,
        `writeable`,
        `note`,
        `hint`
    )
VALUES
    (
        'pgpkeys',
        'blocked',
        NULL,
        10000000,
        0,
        0,
        NULL,
        'NO',
        NULL,
        NULL,
        NULL,
        'decimal',
        '',
        'decimal(25,0)',
        NULL,
        25,
        0,
        NULL,
        'select,insert,update,references',
        1,
        0,
        0,
        '',
        NULL
    ),
    (
        'pgpkeys',
        'encrypted',
        NULL,
        10000000,
        0,
        0,
        NULL,
        'NO',
        NULL,
        NULL,
        NULL,
        'decimal',
        '',
        'decimal(32,0)',
        NULL,
        32,
        0,
        NULL,
        'select,insert,update,references',
        1,
        0,
        0,
        '',
        NULL
    ),
    (
        'pgpkeys',
        'fingerprint',
        '',
        10000000,
        0,
        0,
        '',
        'NO',
        'NO',
        '',
        '',
        'varchar',
        '',
        'varchar(255)',
        255,
        NULL,
        NULL,
        'utf8mb3',
        'select,insert,update,references',
        1,
        0,
        1,
        '',
        NULL
    ),
    (
        'pgpkeys',
        'has_privatekey',
        '',
        10000000,
        0,
        0,
        '',
        'NO',
        '',
        '',
        '',
        'varchar',
        '',
        'varchar(15)',
        15,
        NULL,
        NULL,
        'utf8mb3',
        'select,insert,update,references',
        1,
        0,
        0,
        '',
        NULL
    ),
    (
        'pgpkeys',
        'invalid',
        '',
        10000000,
        0,
        0,
        '',
        'NO',
        '',
        '',
        '',
        'bigint',
        '',
        'bigint(21)',
        NULL,
        19,
        0,
        NULL,
        'select,insert,update,references',
        1,
        0,
        0,
        '',
        NULL
    ),
    (
        'pgpkeys',
        'keyid',
        '',
        10000000,
        0,
        0,
        '',
        'NO',
        'NO',
        '',
        '',
        'varchar',
        '',
        'varchar(255)',
        255,
        NULL,
        NULL,
        'utf8mb3',
        'select,insert,update,references',
        1,
        0,
        1,
        '',
        NULL
    ),
    (
        'pgpkeys',
        'keyname',
        '',
        10000000,
        0,
        1,
        '',
        'NO',
        'NO',
        '',
        '',
        'varchar',
        'PRI',
        'varchar(50)',
        50,
        NULL,
        NULL,
        'utf8mb3',
        'select,insert,update,references',
        1,
        0,
        1,
        '',
        NULL
    ),
    (
        'pgpkeys',
        'privatekey',
        '',
        10000000,
        0,
        0,
        '',
        'NO',
        'NO',
        '',
        '',
        'char',
        '',
        'char(0)',
        0,
        NULL,
        NULL,
        'utf8mb3',
        'select,insert,update,references',
        1,
        0,
        1,
        '',
        NULL
    ),
    (
        'pgpkeys',
        'publickey',
        '',
        10000000,
        0,
        0,
        '',
        'NO',
        'NO',
        '',
        '',
        'text',
        '',
        'text',
        65535,
        NULL,
        NULL,
        'utf8mb3',
        'select,insert,update,references',
        1,
        0,
        1,
        '',
        NULL
    ),
    (
        'pgpkeys',
        'total',
        '',
        10000000,
        0,
        0,
        '',
        'NO',
        '',
        '',
        '',
        'bigint',
        '',
        'bigint(21)',
        NULL,
        19,
        0,
        NULL,
        'select,insert,update,references',
        1,
        0,
        0,
        '',
        NULL
    ),
    (
        'pgpkeys',
        'username',
        '',
        10000000,
        0,
        0,
        '',
        'NO',
        'NO',
        '',
        '',
        'varchar',
        '',
        'varchar(50)',
        50,
        NULL,
        NULL,
        'utf8mb3',
        'select,insert,update,references',
        1,
        0,
        1,
        '',
        NULL
    );

INSERT
    IGNORE INTO `ds_column_list_label` (
        `table_name`,
        `column_name`,
        `language`,
        `label`,
        `xtype`,
        `editor`,
        `position`,
        `summaryrenderer`,
        `summarytype`,
        `hidden`,
        `active`,
        `renderer`,
        `filterstore`,
        `flex`,
        `direction`,
        `align`,
        `grouped`,
        `listfiltertype`,
        `hint`
    )
VALUES
    (
        'pgpkeys',
        'encrypted',
        'DE',
        'encrypted',
        'gridcolumn',
        '',
        999,
        '',
        '',
        1,
        1,
        '',
        '',
        1.00,
        'ASC',
        'left',
        0,
        '',
        NULL
    ),
    (
        'pgpkeys',
        'fingerprint',
        'DE',
        'Fingerprint',
        'gridcolumn',
        '',
        3,
        '',
        '',
        0,
        1,
        '',
        '',
        1.00,
        '',
        '',
        0,
        '',
        NULL
    ),
    (
        'pgpkeys',
        'has_privatekey',
        'DE',
        'has_privatekey',
        'gridcolumn',
        '',
        999,
        '',
        '',
        1,
        1,
        '',
        '',
        1.00,
        'ASC',
        'left',
        0,
        '',
        NULL
    ),
    (
        'pgpkeys',
        'invalid',
        'DE',
        'invalid',
        'gridcolumn',
        '',
        999,
        '',
        '',
        1,
        1,
        '',
        '',
        1.00,
        'ASC',
        'left',
        0,
        '',
        NULL
    ),
    (
        'pgpkeys',
        'keyid',
        'DE',
        'ID',
        'gridcolumn',
        '',
        0,
        '',
        '',
        0,
        1,
        '',
        '',
        1.00,
        'ASC',
        'left',
        0,
        '',
        NULL
    ),
    (
        'pgpkeys',
        'keyname',
        'DE',
        'Name',
        'gridcolumn',
        '',
        1,
        '',
        '',
        0,
        1,
        '',
        '',
        1.00,
        'ASC',
        'left',
        0,
        '',
        NULL
    ),
    (
        'pgpkeys',
        'privatekey',
        'DE',
        'Private Key',
        'gridcolumn',
        '',
        5,
        '',
        '',
        1,
        1,
        '',
        '',
        1.00,
        'ASC',
        'left',
        0,
        '',
        NULL
    ),
    (
        'pgpkeys',
        'publickey',
        'DE',
        'Public Key',
        'gridcolumn',
        '',
        4,
        '',
        '',
        1,
        1,
        '',
        '',
        1.00,
        '',
        '',
        0,
        '',
        NULL
    ),
    (
        'pgpkeys',
        'total',
        'DE',
        'Stimmzettel',
        'gridcolumn',
        '',
        999,
        '',
        '',
        0,
        1,
        '',
        '',
        1.00,
        '',
        '',
        0,
        '',
        NULL
    ),
    (
        'pgpkeys',
        'username',
        'DE',
        'Login',
        'gridcolumn',
        '',
        2,
        '',
        '',
        0,
        1,
        '',
        '',
        1.00,
        'ASC',
        'left',
        0,
        '',
        NULL
    );

INSERT
    IGNORE INTO `ds_column_form_label` (
        `table_name`,
        `column_name`,
        `language`,
        `label`,
        `xtype`,
        `field_path`,
        `position`,
        `hidden`,
        `active`,
        `allowempty`,
        `fieldgroup`,
        `flex`
    )
VALUES
    (
        'pgpkeys',
        'fingerprint',
        'DE',
        'Fingerprint',
        'displayfield',
        'Allgemein/Angaben',
        3,
        1,
        1,
        1,
        '',
        1.00
    ),
    (
        'pgpkeys',
        'keyid',
        'DE',
        'ID',
        'displayfield',
        'Allgemein/Angaben',
        0,
        0,
        1,
        1,
        '',
        1.00
    ),
    (
        'pgpkeys',
        'keyname',
        'DE',
        'Name',
        'displayfield',
        'Allgemein/Angaben',
        1,
        0,
        1,
        1,
        '',
        1.00
    ),
    (
        'pgpkeys',
        'privatekey',
        'DE',
        'Private Key',
        'displayfield',
        'Allgemein/Angaben',
        5,
        1,
        0,
        1,
        '',
        1.00
    ),
    (
        'pgpkeys',
        'publickey',
        'DE',
        'Public Key',
        'displayfield',
        'Allgemein/Angaben',
        4,
        1,
        1,
        1,
        '',
        1.00
    ),
    (
        'pgpkeys',
        'username',
        'DE',
        'Login',
        'displayfield',
        'Allgemein/Angaben',
        2,
        1,
        1,
        1,
        '',
        1.00
    );

INSERT
    IGNORE INTO `ds_reference_tables` (
        `table_name`,
        `reference_table_name`,
        `columnsdef`,
        `active`,
        `constraint_name`,
        `searchable`,
        `autosync`,
        `position`,
        `path`,
        `existsreal`,
        `tabtitle`
    )
VALUES
    (
        'pgpkeys',
        'view_stimmen_je_urne',
        '{\"view_stimmen_je_urne__keyname\":\"pgpkeys__keyname\"}',
        1,
        'manual_586aa44aecdca99d29d97ae2019ca5df',
        0,
        0,
        999,
        '\'\'',
        1,
        ''
    );

INSERT
    IGNORE INTO `ds_access` (
        `role`,
        `table_name`,
        `read`,
        `write`,
        `delete`,
        `append`,
        `existsreal`
    )
VALUES
    ('administration', 'pgpkeys', 1, 1, 1, 1, 0),
    ('_default_', 'pgpkeys', 1, 0, 0, 0, 0);

INSERT
    IGNORE INTO `ds_renderer` (
        `table_name`,
        `pug_template`,
        `label`,
        `orientation`,
        `useremote`
    )
VALUES
    ('pgpkeys', 'pruefziffer', 'Urnenbericht', '', 0);