INSERT INTO
    `ds_renderer_stylesheet` (`classname`, `group`)
VALUES
    (':root', 10),
(':root', 12),
('abel-header', 4),
('address', 1),
('anzeige_name', 3),
('background-image', 4),
('background-image:after', 4),
('ballotpaper-hint', 4),
('bg-color-blue', 7),
('bg-color-blue > .container > .row > .col > p', 7),
('bg-color-dark', 4),
('bg-color-darkgrey', 7),
('bg-color-gray', 7),
('bg-color-green', 7),
('bg-color-light', 4),
('bg-color-lightblue', 7),
('bg-color-white', 7),
('bp-bg-dark', 5),
('bp-bg-dark-disabled', 5),
('bp-bg-darkx', 4),
('bp-bg-light', 5),
('bp-bg-light-disabled', 5),
('bp-bg-lightgray', 5),
('bp-bg-mid', 5),
('bp-bg-mid-disabled', 5),
('bp-bg-midx', 4),
('bp-border-none', 5),
('bp-btn-border', 5),
('bp-btn-button', 5),
('bp-btn-filled', 5),
('bp-btn-large', 5),
('bp-btn-link', 5),
('bp-color-black', 5),
('bp-color-blue', 9),
('bp-color-blue-light', 7),
('bp-color-dark', 5),
('bp-color-gray', 7),
('bp-color-green', 5),
('bp-color-red', 5),
('bp-color-white', 5),
('bp-color-white > p > a, .bp-color-white > a', 9),
('bp-fs-large', 5),
('bp-fs-large > h1,h2', 5),
('bp-fs-normal', 5),
('bp-fs-small', 5),
('bp-fs-xlarge', 5),
('bp-fs-xlarge >  h3', 5),
('bp-fs-xlarge > h1,h2', 5),
('bp-fs-xlarge > h4', 5),
('bp-fs-xxlarge', 5),
('bp-fw-bold', 5),
('bp-lh-large > img', 9),
('bp-link-white-blue', 7),
('bp-link-white-blue:hover', 7),
('bp-link-white-white', 7),
('bp-link-white-white:hover', 7),
('bp-paragraph-li', 5),
('bp-paragraph-li-nr', 5),
('bp-paragraph-li-span', 5),
('bp-paragraph-ul', 5),
('bp-underline-border', 5),
('bp-x-img', 5),
('branding', 4),
('branding a img', 4),
('bt > h3', 7),
('bt>p', 7),
('bt>p:nth-child(2) > strong:nth-child(1)', 7),
('bt>p:nth-child(2) > strong:nth-child(2)', 7),
('bt>p:nth-child(3)', 7),
('btn-color-green-white', 7),
('btn-color-green-white:hover', 7),
('btn-color-logout', 4),
('btn-color-red-white', 7),
('btn-color-red-white:hover', 7),
('btn-color-white-blue', 7),
('btn-color-white-blue:hover', 7),
('btn-color-white-green', 7),
('btn-color-white-green:hover', 7),
('btn-logout', 7),
('btn-margin-left', 7),
('btn-primary', 10),
('buttons', 10),
('candidate-check', 4),
('candidate-content > div > span > strong', 7),
('candidate-content-tr', 7),
('candidate-line', 4),
('candidate-portrait', 4),
('candidatetable', 3),
('circle-checkbox[type=\"checkbox\"]', 11),
(
        'circle-checkbox[type=\"checkbox\"] + label div',
        11
    ),
(
        'circle-checkbox[type=\"checkbox\"] + label div i',
        11
    ),
(
        'circle-checkbox[type=\"checkbox\"]:checked + label div i',
        11
    ),
(
        'circle-checkbox[type=\"checkbox\"]:checked:disabled + label div i',
        11
    ),
('claim', 4),
('claim', 10),
('claimparagraph', 4),
('color-white', 4),
('column-bgkl', 10),
('con-img > p > img', 7),
('contact-bubble', 8),
('contact-bubble-text', 8),
('contact-bubble-text:focus', 8),
('contact-bubble-text:hover', 8),
(
        'contact-bubble:hover ~ div.contact-bubble-text',
        8
    ),
('debugborder', 4),
('dimg > p > img', 7),
('footer', 7),
('footerinfoblock', 2),
('footerinfoblocklabel', 2),
('footerinfoblockvalue', 2),
('form-control', 10),
('gradient-dl', 4),
('gradient-ld', 4),
('header-bar', 7),
('header-topbar', 4),
('header-vh-4 > h3', 7),
('headerbanner', 4),
('headerbanner_green', 4),
('hg-line', 4),
('hint-circle-checkbox[type=\"checkbox\"]', 11),
(
        'hint-circle-checkbox[type=\"checkbox\"] + label div div:nth-child(1)',
        11
    ),
(
        'hint-circle-checkbox[type=\"checkbox\"] + label div div:nth-child(1) i',
        11
    ),
(
        'hint-circle-checkbox[type=\"checkbox\"]:checked + label div div:nth-child(1) i',
        11
    ),
(
        'hint-circle-checkbox[type=\"checkbox\"]:checked~.formbox',
        11
    ),
(
        'hint-circle-checkbox[type=\"checkbox\"]:not(:checked)~.formbox',
        11
    ),
('hr_notvoted', 3),
('left-linklist li  a', 7),
('left-linklist li  a:before', 7),
('left-linklist li a:after', 7),
('legitimation > ul', 7),
('lines-button', 4),
('logout', 4),
('menu-line', 4),
('menu-toggle', 4),
('menu-toggle:before', 4),
('mid-linklist li  a', 7),
('midtext-size', 4),
('muc-page', 7),
('muc21-bp-fs > h1', 9),
('muc21-bp-fs > h2', 9),
('muc21-bp-fs > h3', 9),
('muc21-bp-fs > h4', 9),
('muc21-bp-fs-l', 9),
('muc21-bp-fs-n', 9),
('muc21-bp-fs-n-fixed', 9),
('muc21-bp-fs-s', 9),
('muc21-bp-fs-xl', 9),
('muc21-pb-n', 9),
('muc21-pb-xs', 9),
('muc21-pr-xs', 9),
('muc21-pt-n', 9),
('muc21-pt-xs', 9),
('nav-item', 4),
('navbar', 4),
('nowrap', 4),
('number', 3),
('page', 1),
(
        'page-ballotpaper .candidate-portrait, .page-ballotpaper .picture',
        10
    ),
(
        'page-ballotpaper > div > div:nth-child(2) > table > thead > tr > th.check',
        10
    ),
(
        'page-ballotpaper > div > div:nth-child(2) > table > thead > tr > th.check.align-middle > div',
        10
    ),
('page-ballotpaper p', 10),
('page-ballotpaper p.person1', 10),
('page-chooseballotpaper.container-fluid', 10),
('page-chooseballotpaper.row', 10),
('page-claim', 10),
('page-claim.container-fluid', 10),
('page-footer', 10),
('page-footer', 12),
('page-footer .mid-linklist li a', 10),
('page-header', 10),
('page-header > div > div > * > a > img', 10),
(
        'page-header > div > div > div.col.text-end > a',
        10
    ),
(
        'page-header > div > div > div.text-end > div > div > a > i',
        10
    ),
(
        'page-header > div > div > div.text-end > div > div > a > i > span',
        10
    ),
(
        'page-header > div > div > div:nth-child(2) > a > img',
        10
    ),
('page-legitimation-subtext', 10),
('page-legitimation-subtext > div.container', 10),
('page-login > div > div:nth-child(2)', 10),
(
        'page-logout.container-fluid > div > * > div > a',
        10
    ),
('pagebackground', 1),
('pagecontent', 1),
('pageinfo', 1),
('pagemargins', 1),
('rank', 3),
('sec > p:nth-child(4) > em', 7),
('senderaddress', 1),
('step', 4),
('stepparagraph', 4),
('sz-header-text', 4),
('szg-header-sitze', 4),
('szg-header-text', 4),
('td_notvoted', 3),
('text-contour', 10);

INSERT INTO
    `ds_renderer_stylesheet_groups` (`id`, `name`)
VALUES
    (5, 'ballotpaper'),
    (11, 'checkbox'),
    (8, 'contact-bubble'),
    (2, 'FOOT'),
    (12, 'ihk-default-theme'),
    (1, 'LETTER-ISO-5008'),
    (6, 'menu-toggle'),
    (9, 'muc21'),
    (7, 'style2021muc'),
    (3, 'TABLE'),
    (10, 'wms'),
    (4, 'wmsite');